### ISSUE TITLE
V.6.0.0 asr_train with transformer raise error

### ISSUE THREAD

**Issue by Fhrozen** [espnet/espnet#1093]
Given that the argument `atype` was moved to e2e_asr.py, the asr.py will raise error in chainer backend when the config is set to train the transformer.

```
Traceback (most recent call last):
  File "/export/db/espnet/egs/voxforge/asr1/../../../espnet/bin/asr_train.py", line 341, in <module>
    main(sys.argv[1:])
  File "/export/db/espnet/egs/voxforge/asr1/../../../espnet/bin/asr_train.py", line 325, in main
    train(args)
  File "/export/db/espnet/espnet/asr/chainer_backend/asr.py", line 81, in train
    if args.atype not in ['noatt', 'dot', 'location']:
AttributeError: 'Namespace' object has no attribute 'atype'
```

not sure if it is required to remove:

```python
    # check attention type
    if args.atype not in ['noatt', 'dot', 'location']:
        raise NotImplementedError('chainer supports only noatt, dot, and location attention.')
```
or not move to another part. Let me know to submit a PR

**Comment by kan-bayashi** [comment]
It seems that following lines are duplicated.
https://github.com/espnet/espnet/blob/8c810b713b0b47b94e8bf4faed33d5d7eb1e5a42/espnet/asr/chainer_backend/asr.py#L80-L82
https://github.com/espnet/espnet/blob/8c810b713b0b47b94e8bf4faed33d5d7eb1e5a42/espnet/nets/chainer_backend/rnn/attentions.py#L248-L258

We should remove first one.
BTW, in the latter one, we should use `raise NotImplementedError` instead of `logging.error` and `sys.exit()`.

**Comment by kan-bayashi** [comment]
Also, this error will be also caused in master.
