### ISSUE TITLE
Some questions about chime4 asr1_multich baseline?

### ISSUE THREAD

**Issue by Rpersie** [espnet/espnet#1163]
Recently, I revisit the multichannel e2e experiments in chime4. I find the baseline system is trained with the multinoisy and si284(WSJ) data. The test noisy data is processed by beamforming. 
But in some paper eg."THE MERL/SRI SYSTEM FOR THE 3RD CHIME CHALLENGE USING BEAMFORMING,ROBUST FEATURE EXTRACTION, AND ADVANCED SPEECH RECOGNITION" , retraining with the beamformed data is useful. So if this comparision is fair?  Should the training data also adds the beamformed data ? Thank you !

**Comment by sw005320** [comment]
I'm a coauthor of this paper but I usually don't include the beamformed data because

1. this does not always improve the performance or this only has marginal performance.
2. we may need to re-train the model every time when we change the front-end.

You're right that it is not completely fair comparisons, but I think this is OK by considering the above fact.

**Comment by Rpersie** [comment]
Thank you!
