### ISSUE TITLE
how much does wordpiece model improve e2e transformer asr models?

### ISSUE THREAD

**Issue by chengmengli06** [espnet/espnet#1226]
how much does wordpiece model improve e2e transformer asr models? What is the accuracy on librispeech if grapheme is used instead of wordpiece using e2e transformer asr model?

**Comment by sw005320** [comment]
I think some recipes (e.g., swbd. Not clearly but the result with the larger BPE unit is better) show the effectiveness of the wordpeiece (BPE) from the grapheme unit. We did not compare the grapheme and wordpeiece (BPE), and always use wordpeiece (BPE) since it takes a very long time to train the grapheme system for Librispeech. 

Note that larger BPE unit --> shorter utterance length --> smaller computational cost.

**Comment by chengmengli06** [comment]
Shorter target sequence length means less error accumulations in decoding, which is important for long sequence prediction. But the vocabulary becomes much larger, which leads to higher computational cost.

**Comment by sw005320** [comment]
Yes, but the computation of that operation (high-dimensional linear matrix and softmax) can be easily accelerated, while the sequential processing is incremental and cannot be easily accelerated.

**Comment by ShigekiKarita** [comment]
https://www.isca-speech.org/archive/Interspeech_2019/pdfs/1938.pdf
In this paper, we used char w/o data aug (see Table 2). Current ESPnet uses sentencepiece (see baseline w/o data aug)
https://github.com/espnet/espnet/blob/master/egs/tedlium2/asr1/RESULTS.md#note-contribution-on-wer

According to these, we reduced WER11.6% (char) -> WER11.0% (sentencepiece) on TED-LIUM2.

**Comment by chengmengli06** [comment]
I find out a bug, the generated word piece has no Z character, which will be mapped to <unk>
