### ISSUE TITLE
how to speed up recognition

### ISSUE THREAD

**Issue by vcjob** [espnet/espnet#1293]
Hello everyone!

To transcribe a wav file I use _recog_wav.sh_.  
Everything works fine, but afaik, model loading takes quite some time. So my idea is to make an API, which will load the models at its start once, and after that will just use loaded into the RAM models. 
Due to run.pl, i'm confused a bit how to make this possible. Do you guys have any suggestion?
I need actually recognize short wavs, so even a half of the second counts.
Thank you a lot!
p.s. I use 1xGPU.

**Comment by sw005320** [comment]
If you check some of our google colab example (https://colab.research.google.com/github/espnet/interspeech2019-tutorial/blob/master/notebooks/interspeech2019_asr/interspeech2019_asr.ipynb), you can find a way to perform ESPnet pure python programing. I believe you can realize your idea by referring this code.

**Comment by takeofuture** [comment]
I have the same issue.
120 secs wav by recog_wav.sh takes 5-6 hours if ngpu=0
I can reduce it by using gpu (ngpu=1) 
But I got GPU Memory allocation error(GPU RAM 4GB) 
if I try to decode 8 mins (480 secs) wav file.
I wonder this is why run.sh stage=5, ngpu set to 0 for CSJ in order to avoid GPU Memoery allocation error.

**Comment by kan-bayashi** [comment]
Basically, we assume that the input utterance are split with a suitable length (e.g. less than 30 sec).
Since the encoder is blstm or Transformer without truncation, if you use very long utterances, it consumes much GPU memory.
For example, if you use 480 sec utterance, the number of frames will 48000.
That is too much for a GPU with 4 GB memory.

**Comment by kan-bayashi** [comment]
> I wonder this is why run.sh stage=5, ngpu set to 0 for CSJ in order to avoid GPU Memoery allocation error.

@takeofuture 
The original data in CSJ is long utterance but it provide the segmentation so split utterances are used for training and evaluation.
And currently we use cpu decoding in the all of the recipes due to historical issue, but in future we will replace cpu decoding with gpu decoding as default.

**Comment by vcjob** [comment]
> If you check some of our google colab example (https://colab.research.google.com/github/espnet/interspeech2019-tutorial/blob/master/notebooks/interspeech2019_asr/interspeech2019_asr.ipynb), you can find a way to perform ESPnet pure python programing. I believe you can realize your idea by referring this code.

Thank you a lot! That's what I've been looking for. I figured it out, and it works now just as I want.
Have a good one!
