### ISSUE TITLE
Why the result with Griffin-Lim algorithm is significantly worse than with vocoder?

### ISSUE THREAD

**Issue by geekboood** [espnet/espnet#1316]
I have listen to the result of `csmsc.fastspeech.v3` and it has both GL and WaveNet sub-directories, but the GL results have apparent electronic sound glitches. But in NVIDIA's WaveGlow paper, the MOS for Griffin-Lim is 3.823 and for WaveNet is 3.885. I also hear the Griffin-Lim results on WaveGlow's homepage (`https://nv-adlr.github.io/WaveGlow`) and their results sound normal.

**Comment by sw005320** [comment]
@kan-bayashi, @r9y9, do you have some comments?

**Comment by kan-bayashi** [comment]
This is because in the case of GL we use inverse mel basis to covert mel filterbank to full spectrogram (80 dim -> 2048 or 1024 dim). In waveglow HP, the spectrogram is natural one i.e., magnitude itself is the same as the groundtruth. To improve the quality of GL, it is necessary to consider the use of additional network for the conversion such as CBHG.
