### ISSUE TITLE
can install in windows?

### ISSUE THREAD

**Issue by lamudazh** [espnet/espnet#1324]
Can this toolkit install in windows?

**Comment by Fhrozen** [comment]
There are some ways to make it work, not fully. But, it also depends for the purpose.
If it is for decoding only or for training. 
I may suggest three solutions (The docker and VM solutions are not consider due to obvious reasons):
- WSL (windows 10 subsystem linux), this could be the simplest way to install. You may no need any modification in the code. **Disadvantage**: It do not support GPU (in any way)

- Windows solo: This is the hardest and may not fully work. Kaldi has an option for building the code in windows so the features are possible to be obtained using kaldi-win. Chainer and Pytorch has GPU packages prepared for windows so the installation of these are also easy. **Disadvantages**: additional tools like Warp-CTC, Chainer-CTC may required to install MSYS2 or CYGWIN to build the code. Then, you can install it with pip. This last is not tested so you could may have more difficulties in the way. In case you want to avoid the use of external tools, you may use built-in CTC (available for chainer only). Furthermore, the recipes will need to be rewritten in batch files, and some instructions may not work or if you want to use bash files, you have to use CYGWIN or any similar.  **Advantage**: You can use GPU for training/decode

- Cross-system: (recommended). I tried with espnet in windows using kaldi built in WSL, and for training (tested), decoding (not-tested) used python install in windows (miniconda). There is few work. You can use the normal bash file executed from cmd with `bash -c run.sh --stop_stage 3`. This will build the datasets for training/testing ASR and LM. For the training, you need a separated batch file and then just only copy the training/decoding instructions found in the bash files.

**Comment by v-yunbin** [comment]
@Fhrozen I install espnet in windows，and i just want to decode tts or asr model but not train model.
when decode in windows, I met errors: `C:\Users\GW00213025\Desktop\espnet-v.0.9.8\espnet-v.0.9.8>python F:\model\tts\ch-tts-inference.py
espnet.nets.pytorch_backend.e2e_tts_transformer:Transformer
Traceback (most recent call last):
  File "F:\model\tts\ch-tts-inference.py", line 33, in <module>
    model = model_class(idim, odim, train_args)
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\espnet-0.9.8-py3.8.egg\espnet\nets\pytorch_backend\e2e_tts_transformer.py", line 520, in __init__
    TTSInterface.__init__(self)
  File "C:\Users\GW00213025\AppData\Local\Programs\Python\Python38\lib\site-packages\espnet-0.9.8-py3.8.egg\espnet\nets\tts_interface.py", line 36, in __init__
    self.reporter = Reporter()
TypeError: 'NoneType' object is not callable`

and  i find that follows codes leads to that erros: `try:
    import chainer
except ImportError:
    Reporter = None
else:

    class Reporter(chainer.Chain):
        """Reporter module."""

        def report(self, dicts):
            """Report values from a given dict."""
            for d in dicts:
                chainer.reporter.report(d, self)`
i feel that decodeing not needs the chainer,right?

**Comment by v-yunbin** [comment]
I have installed espnet  in windows and decode tts model, it works
