### ISSUE TITLE
Error run.sh

### ISSUE THREAD

**Issue by tsxce** [espnet/espnet#1347]
1.I am not sure where the mistake is. Does anyone meet this problem before?:
download_and_untar.sh: Successfully downloaded and un-tarred ./downloads/an4_sphere.tar.gz
stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 8 --write_utt2num_frames true data/test exp/make_fbank/test fbank
utils/validate_data_dir.sh: Successfully validated data-directory data/test
steps/make_fbank_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.

2.By the way, there is a mistake when I "make check_install" in the "tools":
extras/check_dependencies.sh: all OK.
tar xojf sctk-2.4.10-20151007-1312Z.tar.bz2 || \
tar --exclude '*NONE*html' -xvojf sctk-2.4.10-20151007-1312Z.tar.bz2
pyenv: bzip2: command not found

The `bzip2' command exists in these Python versions:
  anaconda3-5.3.1

**Comment by sw005320** [comment]
Could you let me know your environment? Also, did you exactly follow our installation or customize it?

**Comment by xiechen0692** [comment]
Because I want to install including kaldi, so start from ”Step 2-B) installation including Kaldi installation“.
My environment is : PYTHON_VERSION=3.7 TH_VERSION=1.0.1.post2 CUDA_VERSION=9.1
And I run the command: "make -j 10 PYTHON_VERSION=3.7 TH_VERSION=1.0.1.post2 CUDA_VERSION=9.1"
Then run:"cd egs/an4/asr1", "./run.sh --backend pytorch"

**Comment by sw005320** [comment]
ok, can you simply install bzip2 in your environment?

**Comment by xiechen0692** [comment]
Here are my new progress.
First, In the step2-A), I use the kaldi path which I installed before.
After step 2-A, there is a new KALDI in the espnet-master.
Second, I run command"make -j 10’ and "make check_install" check_install shows OK.
Then, I changed the "main root" in the egs/an4/asr1/path.sh first line to espnet-master so that it can find the "/tools/config/common_path.sh". After runnning "bash ./run.sh --backend pytorch", mistakes show up. 
stage -1: Data Download
local/download_and_untar.sh: an4 directory already exists in ./downloads
stage 0: Data preparation
stage 1: Feature Generation
steps/make_fbank_pitch.sh --cmd run.pl --nj 8 --write_utt2num_frames true data/test exp/make_fbank/test fbank

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/fujii/\udce3\udc83\udc87\udce3\udc82\udcb9\udce3\udc82\udcaf\udce3\udc83\udc88\udce3\udc83\udc83\udce3\udc83\udc97/xiechen/espnet-master/tools/venv/lib/python3.7/site-packages/conda/cli/main.py", line 138, in main
        return activator_main()
      File "/home/fujii/\udce3\udc83\udc87\udce3\udc82\udcb9\udce3\udc82\udcaf\udce3\udc83\udc88\udce3\udc83\udc83\udce3\udc83\udc97/xiechen/espnet-master/tools/venv/lib/python3.7/site-packages/conda/activate.py", line 996, in main
        print(activator.execute(), end='')
    UnicodeEncodeError: 'utf-8' codec can't encode characters in position 4000-4017: surrogates not allowed

Is there anything wrong with my progress?
It is possible to use python version of kaldi to process the data?
Thanks a lot for you help!

**Comment by tdeboissiere** [comment]
@xiechen0692 Did you check your audio was at 16000 Hz in16 ?
I had the same error as you with an audio file sampled ad 22050 Hz
