### ISSUE TITLE
How to speed up CPU decoding?

### ISSUE THREAD

**Issue by chrisspen** [espnet/espnet#1380]
I'm finding that ASR works pretty well and has reasonably good accuracy, but the speed is quite slow. The 5-10 sec audio clips I'm testing with take about 5 min each to transcribe using the `recog_wav.sh` script. Is there any way to speed up this performance on a system with no GPU?

**Comment by Fhrozen** [comment]
If you are using pytorch (because it does not use numpy) the only possible solutions I could suggest:
- Reduce the number of `beam-size` to 1 ~5
- Remove the use of LM (This may be harm the performance a lot)
- Try to use Sub-words. Most of the time could be consumed in nets trained at character-level. Sub-word will reduce the length of the output and therefore increase the decoding time.

Probably you could try with the first and the check the others.

**Comment by sw005320** [comment]
Also, we are working on focusing on major speed improvement. Please wait for a month.

**Comment by chrisspen** [comment]
Where would I adjust the beam-size for, say, for the Tedlium3 model? If I search the egs/tedlium3 folder for "beam-size", I find multiple matches.

**Comment by sw005320** [comment]
change https://github.com/espnet/espnet/blob/master/egs/tedlium3/asr1/conf/decode.yaml#L2

**Comment by chrisspen** [comment]
Thanks.
