### ISSUE TITLE
More detail description of pre-trained models (TTS)

### ISSUE THREAD

**Issue by hieuthi** [espnet/espnet#1394]
I am looking for details description of pre-trained acoustic and wavenet models but unable to find them.
As there a lot of new strategies now for training beside the vanilla training intra-corpus (transfer from another models, multispeaker with x-vector). It would be nice to know how exactly the model was train.

In particular. I am looking for description of libritts.wavenet.mol.v1 : 
- Is it trained with libritts?
- Is it used a pre-train model?
- Is it included speaker-embedding (or x-vector) as as saw a parameter ["n_speakers": 7 ]but not sure what it do?

A pointer to the relevant paper (or maybe github development discuss) for each individual pre-trained model is also nice addition as it would be easier to give proper citation.

Thanks.

**Comment by kan-bayashi** [comment]
Hi @hieuthi.
Thank you for your question and suggestion.
At first, I will answer your question.

> Is it trained with libritts?

Yes, the wavenet was trained using LibriTTS dataset.

> Is it used a pre-train model?

Not sure what pre-train model means but this model was trained from scratch.

> Is it included speaker-embedding (or x-vector) as as saw a parameter ["n_speakers": 7 ]but not sure what it do?

No, it did not use any speaker information. The wavenet is only conditioned on Mel spectrogram. That configuration is not used since `gin_channels` is set `-1`. 

I will consider adding the information about PR where the pretrained model was added.

**Comment by hieuthi** [comment]
Thank you for fast response
