### ISSUE TITLE
python 2 and 3 compatible

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#14]
Some people reported an issue due to the python 2 and 3 compatibility.
Right now, the unicode type in python 2 would cause some issues, which are used in everywhere, and need to be fixed.

**Comment by ShigekiKarita** [comment]
For Python2/3 compatibility, I recommend you to use flake8/hacking linter. 

``` console
$ pip install hacking
$ flake8 ./src | grep "Python 3.x"
./src/utils/filt.py:23:17: H233  Python 3.x incompatible use of print operator
./src/utils/filt.py:25:17: H233  Python 3.x incompatible use of print operator
./src/utils/text2token.py:52:9: H233  Python 3.x incompatible use of print operator
./src/utils/text2token.py:87:9: H233  Python 3.x incompatible use of print operator
```

**Comment by kan-bayashi** [comment]
@ShigekiKarita Thank you for your information.
I think at least we should add following lines to be compatible with `python 3`.
`from __future__ import print_function`
`from __future__ import division`

**Comment by ShigekiKarita** [comment]
In my opinion, there are no need to make scripts in `src/utils` python2/3 compatible because they are single-file-complete and only depend on python2 standard lib. Even they do not need venv.

So I propose that we just use a shebang `#!/usr/bin/env python2` instead of `#!/usr/bin/env python` until python2 dies. I've done some exps successful with PR #18

**Comment by sw005320** [comment]
I found that the Unicode issue is affected by `LC_ALL=C` in `path.sh`, which causes issues even we use Python 3. we need some investigation.

**Comment by ShigekiKarita** [comment]
could you share a snippet of LC_ALL affected one ? maybe we can avoid it by unsetting within python 
``` python
import locale
locale.setlocale(locale.LC_ALL, '')
```

**Comment by lahiruts** [comment]
Is it possible to have a readme file with the changes necessary to the master when someone want to use espnet using python 3?
I believe the recommended version to use is python 2.7?

**Comment by sw005320** [comment]
Thanks, I will add it. Our travis CI actually checks both python 2.7 and 3.6 , and basic parts should be OK, but I don't fully test both cases.

**Comment by sw005320** [comment]
@kan-bayashi, I think you're using python 3, right? Do you have any issues now?

**Comment by ShigekiKarita** [comment]
I'm also using python3. I have known some issues like 

- if kaldi installs python2 under tools (it can be happen when your python is 3), path.sh prefer kaldi’s python
- makefile has some hard coded lines like venv/lib/python2.7
- some utill scripts still have `#!/usr/bin/env python` but it should be `#!/usr/bin/env python2` because it is not compatible to python3 and do not use third party modules.

**Comment by ShigekiKarita** [comment]
TravisCI should use tools/Makefile to setup but kaldi is a problem. It took too long time to install and there is no test requires  kaldi when I setup the CI. I think Makefile
 should skip the kaldi build under the CI somehow.

I think many users do not compile kaldi everytime , they might put a link in tools/kaldi or install via conda

**Comment by lahiruts** [comment]
@ShigekiKarita you are correct. I also use a link to my Kaldi installation under the tools folder.
