### ISSUE TITLE
Confusion about knowledge distillation of FastSpeech

### ISSUE THREAD

**Issue by nanma** [espnet/espnet#1400]
The FastSpeech paper said, ‘We feed the text and speech pairs in the training set to the model again to obtain the encoder-decoder attention alignments, which are used to train the duration predictor’(In section 4.3 of the paper). 

I guess feeding text and speech pairs to Transformer TTS means the inference procedure is in Ground Truth Aligned(GTA) mode, otherwise there is no need to feed the speech part and the alignments may not be correct in non-GTA mode. Thus the alignments obtained here is in accordance with the ground truth speech.

On the other hand, the authors said ‘For each source text sequence, we generate the mel-spectrograms with the autoregressive Transformer TTS model and take the source text and the generated mel-spectrograms as the paired data for FastSpeech model training’. These mel-spectrograms are generated only from the source text, thus their lengths may not be compatible with the ground truth speech, since this generation procedure is not in GTA mode.

Here comes my question, when training the FastSpeech model together with the duration predictor, the target mels(non-GTA mode) for FastSpeech and the target alignments(GTA mode) for the duration predictor mentioned above are not compatible.

I find the ESPnet implementation of [FastSpeech](https://github.com/kan-bayashi/espnet/tree/feature/knowledge_dist) seems to use only text to generate alignment, which does not completely match the original paper.

How to resolve this conflict? Or do I misunderstand the paper.

**Comment by kan-bayashi** [comment]
Hi @nanma. Thank you for your question.
In the current master, we did not use knowledge distillation. Here, "do not use knowledge distillation" means that the target duration is generated by the teacher Transformer with teacher forcing. The teacher Transformer received the text and ground truth of feature sequences and then we can calculate the duration of each input token. The current implementation does it on the fly during training.

In #1287, I'm developing knowledge distillation.
In this implementation, first, we generate the feature sequences and the duration by using the teacher Transformer with auto-regressive generation and dump them.
And then, FastSpeech is trained using the generated feature as the target feature sequence and the duration as the target of Duration Predictor. The point is that here we do not use any ground truth feature sequence, use only the text. In other words, in the case of knowledge distillation, actually, we do not need to prepare the ground-truth of the target feature sequence. Just using text is enough. So if we use knowledge distillation, it is easy to augment the training data because what we need to prepare is just text.

**Comment by nanma** [comment]
@kan-bayashi Thanks for your detailed answer！
I thought more about this training procedure based on your reply and the original paper, and I thought your implementation is in consistent with the paper, which is:

1. For training FastSpeech without knowledge distillation, use both text and ground truth feature sequences;
2. For training FastSpeech with knowledge distillation, use only text to generate target feature sequences and target alignments.

Since the teacher model may generate error with text as input, certain procedure to filter these wrong targets would be necessary for good training performance.

**Comment by kan-bayashi** [comment]
> Since the teacher model may generate error with text as input, certain procedure to filter these wrong targets would be necessary for good training performance.

Right. Now I'm considering the good filtering method.
