### ISSUE TITLE
ESPnet2 development discussion

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#1425]
- This is an issue to discuss #1372 
- python 3.7 is too aggressive (?) by @r9y9

links
- espnet2 modules https://github.com/espnet/espnet/tree/v.0.7.0/espnet2
- espnet2 examples https://github.com/espnet/espnet/tree/v.0.7.0/egs2

**Comment by geekboood** [comment]
I also encounter some inconvenience when I use espnet. 
Firstly, as a PyTorch user, I agree that we should have a kaldi and chainer free version. I have seen both a python script uses librosa and a kaldi script to extract features, which is confusing. I think a pure python version and use librosa library could be more convenient. Also, my [previous issue](https://github.com/espnet/espnet/issues/1345) mentions that I found a problem when I try to train the model. I think chainer could be the reason of the problem and utilize all my 16 cores 100%. 
Secondly, many models rely on each other. When I want to use models from espnet elsewhere, I cannot install espnet and the whole kaldi. All I want is just a TTS or ASR model and inference it. When I wanted to use fastspeech model, I found that it relies on transformer model and a bunch of tools from RNN, etc. When I wanted to train transformer TTS model in FP16, a single usage of NVIDIA's apex library is not enough because of some tensor type problems when the model plots the attention figure.

**Comment by kamo-naoyuki** [comment]
>     * python 3.7 is too aggressive (?) by @r9y9

This is about this part of my PR:

https://github.com/espnet/espnet/blob/f5d6c4ee0e48b87205e0af940d3aadaaf83e9aa4/setup.py#L10-L13

Basically I'm always aggressive about Python version, so I have used 3.7's features in espnet2 without thinking much.  please notify me if there are already any dependencies problems @r9y9 
The default python installed by Anaconda is 3.8., I have tested now, so I think this is not so aggressive?

The most strong motivation is that python<=3.6, with UNIX OS, the value of `sys.getfilesystemencoding()`, which is refered as `file system encoding` and used in `open()` for example, depends on the locale, `LC_LANG`. Unbelievable...
This value can't  be changed by any other ways including `PYTHONDEFAULTENCODING` in my understanding.

In python>=3.7, the default value is `UTF-8` if using UTF-8 mode and the mode is enabled by default even if using UNIX OS. Indeed I haven't met the encoding issues since I used Python3.7.

https://docs.python.org/3.7/library/sys.html#sys.getfilesystemencoding

**Comment by r9y9** [comment]
What I wanted to say is that dropping support for a specific version of python, which is still widely used in the python community, is an aggressive decision. The decision may throw potential users away. In my opinion (philosophy?), we should generally try to give broader support to make the software available to as many users as possible. I know espnet is more like a research project and going fast and fast, but it would be great to think more about broader users.

Well, perhaps I'm the minority; I'm not using espnet's default python and I still use python 3.6 (setup done with my own anaconda).

As for the getfilesystemencoding problem, I have never come across a situation that matters. However, if you guys think the feature in python 3.7 is really important, that would be okay. Though, dropping support silently is not a friendly way to go ahead; we'd better discuss/annouce it in advance.

**Comment by r9y9** [comment]
By the way, my *personal* reason not feeling like to move to python 3.7 is https://github.com/MattShannon/bandmat/issues/10#issuecomment-497389270; still not resolved yet :(

**Comment by kamo-naoyuki** [comment]
@r9y9 I agree it is better to support widely. You are right in general as we can't estimate the hidden user's to leave with strict requirements, of course, so this is just a philosophy problem. If for personal project, I never made such decision.

The encoding problem is not fatal issue for mature programmer as you, it's just using `open(encoding="utf8")` if setting `LC_ALL=C`, but for  beginner the behaviour related to Python's encoding is too complex. I put the priority easily to join for low skill developpers rather than kindly to be used by more not researcher people. 

About cython's issue, I don't understand the reason correctly, maybe, in my memory, such problem can be solved to regenerate c code easily, isn't it?

**Comment by kamo-naoyuki** [comment]
The features I used of Python3.7 are:

- dataclass: https://docs.python.org/3/library/dataclasses.html
- `from __future__ import annotation`
- open() without encoding; we always set LC_ALL=C for sorting order in `path.sh`.
It's not hard to take back 3.6 for now. Actually I'd like to use 3.8, it has many attractive features...

**Comment by kan-bayashi** [comment]
For encoding, PYTHONIOENCODING=UTF-8 is not working well?

**Comment by ShigekiKarita** [comment]
@geekboood thanks for comments

> Also, my previous issue mentions that I found a problem when I try to train the model. I think chainer could be the reason of the problem and utilize all my 16 cores 100%.

espnet2 will solve this by pytorch DataLoader.

> Secondly, many models rely on each other ... because of some tensor type problems when the model plots the attention figure.

@kamo-naoyuki made excellent changes on this. For example, espnet2 unified encoder/decoder interface that can compose RNN/Transformer/etc modules 
- https://github.com/espnet/espnet/blob/v.0.7.0/espnet2/asr/encoder/abs_encoder.py
- https://github.com/espnet/espnet/blob/v.0.7.0/espnet2/asr/decoder/abs_decoder.py

and also attention plot in a clean implementation
- https://github.com/espnet/espnet/blob/v.0.7.0/espnet2/utils/calculate_all_attentions.py

> All I want is just a TTS or ASR model and inference it.

I see. That is really important. Maybe after finishing espnet2, we can put our pretrained models in somewhere like https://pytorch.org/hub/

**Comment by kamo-naoyuki** [comment]
(The discussion for Python version is not high priority matter, so I finished to put comments, sorry @r9y9, and thanks)

@kan-bayashi 
In my understanding, PYTHONIOENCODING has effects only for stdout and stdin.

```python
import sys 
import locale
print(sys.getdefaultencoding())
print(sys.getfilesystemencoding())
print(sys.stdout.encoding)
print(locale.getpreferredencoding())
```

```
#  PYTHONIOENCODING=utf-8 LC_ALL=C python3.6
ascii
ANSI_X3.4-1968
utf-8
ANSI_X3.4-19
```

```
#  LC_ALL=C python3.7
utf-8
utf-8
UTF-8
UTF-8
```

Python uses many variables for encoding and they can have different values each other and I forget this complex system sometimes.

**Comment by sw005320** [comment]
I personally like the idea of using the latest (stable) python for this project. It yields better design and simpler codes than updating the python version later.

**Comment by Fhrozen** [comment]
FYI, in the example code : `python -m espnet2.bin.asr_train --print_config --optimizer adam --encoder_decoder transformer`
is written but the option `--optimizer` is `--optim`, Maybe this will be confusing for the documentation.

**Comment by kamo-naoyuki** [comment]
@Fhrozen o.k. thanx. l ll fix. 

l couldn't decide such short word is better or formal is better.

**Comment by sanzimu** [comment]
RuntimeError happened to me when i run with docker ; RuntimeError: cannot cache function '__shear_dense' : no locator available for file librosa/util/utils.py ; the version of librosa 0.7.x will cause the error

**Comment by sw005320** [comment]
> RuntimeError happened to me when i run with docker ; RuntimeError: cannot cache function '__shear_dense' : no locator available for file librosa/util/utils.py ; the version of librosa 0.7.x will cause the error

we did not prepare the docker image for espnet2 yet.

**Comment by sw005320** [comment]
I commented on several ideas in https://github.com/espnet/espnet/pull/1439#issuecomment-565854783. These are basically about the model ecosystem.

**Comment by Peidong-Wang** [comment]
Nice job on #1372 @kamo-naoyuki ! I personally like a feature extracting features from wav files on the fly (on GPU) to achieve "real" end-to-end processing. What is your opinion?

**Comment by kamo-naoyuki** [comment]
@Peidong-Wang ESPnet2 adopts feature extraction in the model by default and also supports the training using the prepared features both.

**Comment by Peidong-Wang** [comment]
> @Peidong-Wang ESPnet2 adopts feature extraction in the model by default and also supports the training using the prepared features both.

Thanks. I would also like a MWER training objective function. What do you think of it?

**Comment by kamo-naoyuki** [comment]
@Peidong-Wang Please throw a feature request in another thread. 
ESPnet2 is just a refactoring project and any essential features shouldn't be discussed in espnet2 if it can be also in espnet1.

I haven't used something like MWER for att based ASR personally and I don't know whether it is successful. Do you have some results?
