### ISSUE TITLE
VRAM is distributed unequally when training Tacotron2 on Muti-GPUs（3）

### ISSUE THREAD

**Issue by JoeyHeisenberg** [espnet/espnet#1467]
VRAM is distributed unequally when training Tacotron2 on 3-GPUs (batch_size=10->10*3).
Though it did accelerate the training speed, I still want to set bigger batch_size to make it faster. 
All GPUs will get their own batch_size data and pass the updated parameters to GPU:0 to caculate , It seems unreasonable that the need of GPU:0 VRAM is ten times bigger than other GPUs?

![image](https://user-images.githubusercontent.com/33407667/71430395-7dad0700-2706-11ea-90e0-aa912388f914.png)

**Comment by kan-bayashi** [comment]
Maybe this is because `batch-sort-key: shuffle`.
https://github.com/espnet/espnet/blob/1468ee0c1aaab1ffbc6d3247e7e0e3987e08117c/egs/ljspeech/tts1/conf/tuning/train_pytorch_tacotron2.v3.yaml#L39
In that case, the length of each item in batch is different.
Each item is sorted according to the length and then split into 3 gpus.
Therefore, the first split batch is bigger than the remaining batches.

To solve this issue, let us use `batch-sort-key: input or output` or `batch-bins` instead of `batch-size`.
https://github.com/espnet/espnet/blob/1468ee0c1aaab1ffbc6d3247e7e0e3987e08117c/egs/m_ailabs/tts1/conf/tuning/train_pytorch_tacotron2.v3.yaml#L38
In the both case, we perform sorting according to the length and then make the batch. Therefore, the length of each item in batch is almost the same.

**Comment by JoeyHeisenberg** [comment]
how much should I set the batch-bins？what is the meaning of 870 and 180 in batch-bins（80 is the dimention of mel spctrogram and 35 is the dimention of char）

**Comment by kan-bayashi** [comment]
Maximum or average length of output and input.
See more info at
https://github.com/espnet/espnet#how-to-set-minibatch

**Comment by JoeyHeisenberg** [comment]
@kan-bayashi  It did work, thx.  And I found some samples which have long input len and deleted it, guessing these do harm to the training

**Comment by JoeyHeisenberg** [comment]
![image](https://user-images.githubusercontent.com/33407667/71439956-959c7f00-2736-11ea-986f-20db0ba82f85.png)
->
![image](https://user-images.githubusercontent.com/33407667/71439962-99c89c80-2736-11ea-8223-27f6bb22a1d6.png)
really help a lot

**Comment by kan-bayashi** [comment]
Great!
