### ISSUE TITLE
Some questions regarding espnet speech to text toolkit

### ISSUE THREAD

**Issue by samin9796** [espnet/espnet#1469]
1. Is it possible to train without building a phonetic dictionary? I want to work on Bengali language but there are not such dictionaries in this language.

2. Is rnn transducer implemented in espnet?

3. In the installation guide, the link provided to install both kaldi and espnet using miniconda is broken. Can you provide some clear documentation on how to install espnet using docker and without using docker?

**Comment by kan-bayashi** [comment]
Hi @samin9796. I will answer your questions.

> Is it possible to train without building a phonetic dictionary? I want to work on Bengali language but there are not such dictionaries in this language.

Yes, since our model is based on an end-to-end manner, the phonetic dictionary is not needed.

> Is rnn transducer implemented in espnet?

Yes. Both RNN-transducer and Attention RNN-trunsducer are available. You can try it in some recipes e.g. `egs/voxforge/asr1`. This is the configuration example.
https://github.com/espnet/espnet/blob/master/egs/voxforge/asr1/conf/tuning/transducer/train_transducer.yaml

> In the installation guide, the link provided to install both kaldi and espnet using miniconda is broken. Can you provide some clear documentation on how to install espnet using docker and without using docker?

Oh, sorry the link to miniconda is expired.
But the installation procedure is written in our README.
Please follow it.
- For non-docker: https://github.com/espnet/espnet#installation
- For docker: https://github.com/espnet/espnet/blob/master/docker/README.md

**Comment by samin9796** [comment]
@kan-bayashi Thanks a lot for your answers. I just want to be sure that as espnet uses kaldi style data preprocessing, then I can use grapheme instead of phoneme in the lexicon file, right? Is there any advantages or disadvantages of using docker? What would you recommend?

**Comment by kan-bayashi** [comment]
Yes, we use kaldi style data prep but what we need to prepare is only wav.scp, utt2spk, spk2utt, and text. The other files are not needed.

About the advantage of the use of docker, it depends on your environment and purpose. If you use the container job manage system like kubeflow or your machine’s OS is not standard one, it is convenient, I think.
