### ISSUE TITLE
Back transformation fbanks to wav file

### ISSUE THREAD

**Issue by kobiche** [espnet/espnet#1496]
Hi, I've been trying to transform back the input of the encoder (attention location-aware mechanism) to a wav file using the function convert_fbank_to_wav.py. Just to be sure that I understand how it works, I decoded a sample (using the recog_wav.sh) and gave the path to the fresh extracted  feature banks:

`python3 convert_fbank_to_wav.py --filetype mat --fs 16000 --n_mels 83 scp:/PATH/TO/FEATURES/orig/dump/feats.1.scp ~/Desktop/test_wav`

The sampling frequency and the number of mel banks were both taken from the egs/tedlium2/asr1/conf/fbank.conf file, which I believe is used for the feature extraction. 

The problem is that the output of the function is totally nonsensical. It is mostly noise. Where did I go wrong?

**Comment by sw005320** [comment]
@kan-bayashi, can you comment about it?

**Comment by kan-bayashi** [comment]
Hi @kobiche.
Fbank feature for ASR is different from that for TTS.
For ASR, we use 80 fbank + 3 dim pitch features extracted by kaldi.
For TTS, we use 80 fbank extracted by librosa.
`convert_fbank_to_wav.py` is designed to use with TTS features.

In your case, the feature includes pitch features so the results will be wrong.

**Comment by kobiche** [comment]
Is there any way to convert back to the original wav file?

**Comment by kan-bayashi** [comment]
For ASR features, there is no such a function.
If you use utils/compute-fbank-feats.py to extract fbank, it can be.

**Comment by iustinaabc** [comment]
Hi,

**Comment by iustinaabc** [comment]
Hi, I have a related issue.
In my application I need to invert some adversarial features created with ESPnet for the VoxForge ASR task. As such, instead of using Kaldi's feature extraction (_compute-fbank-pitch_), I used the Librosa-based **compute-fbank-feats.py** to get 80 mel-fbanks from regular input wavs, and then applied convert_fbank_to_wav.py to invert those features, just as a sanity check. However, after inversion I get wav files that only have 0's. My parameters for both forward and inverse functions are:
fs=16000
fmax=7800
fmin=80
n_fft=512
n_shift=160
win_length=512
n_mels=80
iters=64
window='hann'
I was wondering where the problem lies.

**Comment by kan-bayashi** [comment]
@iustinaabc Did you perform de-normalization?
 If you apply to normalized feature, the power is very small so it will be almost zero.

**Comment by iustinaabc** [comment]
I did not apply any CMVN in the forward feature extraction. The only normalization was the implicit scaling done in **compute-fbank-feats.py**
```
array = array / (1 << (args.normalize - 1)) 
# normalize = bit depth of the PCM for normalizing data to scale in [-1,1]
```

I tried to debug this separately in a jupyter notebook - I loaded the features for a single audio utterance and did plots at different stages of the feature inversion. There seems to be some signal after griffin_lim is applied:
![image](https://user-images.githubusercontent.com/46626614/75030576-ad795080-54a4-11ea-9a2f-8f4331aacb28.png)

The problem seems to occur after I write this waveform to a .wav file and then reload it - it'll have only 0s. So the problem seems to be in these lines from  **compute-fbank-feats.py**
```
write(args.outdir + "/%s.wav" % utt_id,
              args.fs,  (y * np.iinfo(np.int16).max).astype(np.int16))
```

**Comment by iustinaabc** [comment]
I did this from scratch and inversion worked, with audio sounding very close to the original. There must have been a parameter mismatch somewhere, but didn't investigate further.

**Comment by JaejinCho** [comment]
> Hi @kobiche.
> Fbank feature for ASR is different from that for TTS.
> For ASR, we use 80 fbank + 3 dim pitch features extracted by kaldi.
> For TTS, we use 80 fbank extracted by librosa.
> `convert_fbank_to_wav.py` is designed to use with TTS features.
> 
> In your case, the feature includes pitch features so the results will be wrong.

@kan-bayashi Do you know by any chance the parameter values to extract fbank in Kaldi that corresponds to fbank extracted by librosa?

**Comment by kan-bayashi** [comment]
@JaejinCho Sorry, I'm not familiar with kaldi's implementation. I have no idea about it.

**Comment by kamo-naoyuki** [comment]
> @kan-bayashi Do you know by any chance the parameter values to extract fbank in Kaldi that corresponds to fbank extracted by librosa?

Impossible. There are some fashions  for mel-filter bank and Kaldi's filter is different from librosa, but torchaudio supports it, https://pytorch.org/audio/compliance.kaldi.html#functions

The implementation looks same as Kaldi as I read.

**Comment by JaejinCho** [comment]
I see. Thank you all for the answers.

**Comment by fclearner** [comment]
@iustinaabc Hi, I met the same problem as you described, and i debug it finding that before write to wav
"write(
            args.outdir + "/%s.wav" % utt_id,
            args.fs,
            (y * np.iinfo(np.int16).max).astype(np.int16),
        )",
the y is too big to use np.int16, therefore it all becomes zero, I try to make a normalization before writing to wav file, it seems the back-transformed waveform is normal, but the audio doesn't sound right, maybe something wrong with the parameter or function
