### ISSUE TITLE
Recipe-related questions for new corpora [not ports]

### ISSUE THREAD

**Issue by AdolfVonKleist** [espnet/espnet#1503]
Hi, I'm interested in potentially contributing espnet recipes for two Swiss corpora:

Swiss French Polyphone :
- http://catalog.elra.info/en-us/repository/browse/ELRA-S0030_02/ 

Swiss German Polyphone (aggregate of Speech DAT (I) and Speech DAT (II)
- http://catalog.elra.info/en-us/repository/browse/ELRA-S0096/
- https://catalogue.elra.info/en-us/repository/browse/ELRA-S0105/

Both are telephony databases focused on regional variants and several dialects of these languages as spoken in Switzerland.  These are both somewhat niche, and have not enjoyed too much attention in recent years, but they might make interesting additions. They are however well-organized and each contains well over 200hrs of training data. It would be great to breathe some new life into them.

Before taking it any further I would like to ask a couple of questions:

- Is there interest in these additions? 
- These corpora are available for purchase via ELRA, but they are not public/free; I assume this is not an issue as many kaldi recipes are subject to the same constraints, but would like to confirm.
- There are no Kaldi recipes for these corpora.  Is this a problem?
- There are no 'standard' train/dev/test splits either, do you have preferred guidelines for creating them in this case?
- Following this repo for a while I note the recent move to v2, and the same in the recipes section.  v2 appears to come with a template generator for the recipes; would it be best to just start there, or should v1 and v2 recipes be supplied?

The outcomes I've seen with this framework so far have been really impressive.

**Comment by sw005320** [comment]
Thanks for your great suggestions!

> * Is there interest in these additions?

Definitely.

> * These corpora are available for purchase via ELRA, but they are not public/free; I assume this is not an issue as many kaldi recipes are subject to the same constraints, but would like to confirm.

Right. This is no problem.

> * There are no Kaldi recipes for these corpora.  Is this a problem?

No problem.
We have several such recipes.

> * There are no 'standard' train/dev/test splits either, do you have preferred guidelines for creating them in this case?

Ideally, it would be better to make them open for both speaker IDs and transcriptions.
In the hybrid system, people only care about the speaker ID overlap, but in the end-to-end system, we should also consider the transcription overlaps across training and test data.
This is because the end-to-end system also includes language modeling and the decoder network can be easily over-tuned with the text patterns that appeared in the training data. 
If the test data includes the same transcription, this over-training causes some confusion.

> * Following this repo for a while I note the recent move to v2, and the same in the recipes section.  v2 appears to come with a template generator for the recipes; would it be best to just start there, or should v1 and v2 recipes be supplied?

My suggestion is to start with v1.
v2 is not fully fixed yet (may take time although we try to finish it as soon as possible).
The conversion to v2 is not so difficult.

> The outcomes I've seen with this framework so far have been really impressive.

Thanks a lot!

**Comment by AdolfVonKleist** [comment]
Great, thank you very much for the info!  We will cobble together a draft for review with this information in mind.
