### ISSUE TITLE
Pure CTC decoding bug

### ISSUE THREAD

**Issue by luyizhou4** [espnet/espnet#1508]
Hi, there!

I'm currently decoding my CTC model (mtlalpha 1.0) with pure CTC mode (ctc_weight 1.0), and find that in current implementation, ctc-prefix-search will also compute \<blank\> token's next-label-score, which to my understanding shall be excluded. Details below: 

With ctc_weight=1.0, **ctc_beam** becomes the size of whole vocabulary (including \<blank\> token)

https://github.com/espnet/espnet/blob/28ce90a17148afcb36f4e593966911b9c3a6230b/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L291-L296

Then \<blank\> token-id will be included in **local_best_ids**, and prefix-score computed. To my understanding, \<blank\> should be excluded here.

https://github.com/espnet/espnet/blob/28ce90a17148afcb36f4e593966911b9c3a6230b/espnet/nets/pytorch_backend/e2e_asr_transformer.py#L328-L335

**Comment by sw005320** [comment]
I see.
Did you find any degradation?

@takaaki-hori, I think we should not consider the blank.
Can you check it?

**Comment by takaaki-hori** [comment]
Yeah, the array `local_best_ids` should not include 0 (\<blank\>).
When ctc_weight != 1, there is no problem since the attention model gives a very low probability to \<blank\>, and `local_best_ids` does not include 0.
But, if ctc_weight = 1,  `local_best_ids` has all IDs.
So, we need to exclude 0 from `local_best_ids`, e.g., by making it with np.arange(1, odim).
It is also possible that we always set zero to the prefix probability for \<blank\> in CTCPrefixScore.
Anyway, I will handle this matter.

**Comment by sw005320** [comment]
Thanks!

**Comment by luyizhou4** [comment]
Thanks for reply! Excluding 0 from local_best_ids improves my CTC result from 12.54% to 12.08%, and for reference greedy decoding WER is 12.10%.

**Comment by sw005320** [comment]
thanks, this is significant.

**Comment by sw005320** [comment]
@takaaki-hori, could you think of fixing this?

**Comment by takaaki-hori** [comment]
Yes, I am working on it now.
