### ISSUE TITLE
Pretained Model Needed for SemiSupervised Librispeech 

### ISSUE THREAD

**Issue by takeofuture** [espnet/espnet#1516]
I just started to modify JSUT recipe to make it ASRTTS
Ref:
https://github.com/espnet/espnet/pull/818/files
creatorscan:asrtts3-v.0.7.0

After Stage 1, I found the above ASRTTS recipe uses X-Vector Pretained Model (English)
```
    # Check pretrained model existence
    if [ ! -e ${nnet_dir} ];then
        echo "X-vector model does not exist. Download pre-trained model."
        wget http://kaldi-asr.org/models/8/0008_sitw_v2_1a.tar.gz
        tar xvf 0008_sitw_v2_1a.tar.gz
        mv 0008_sitw_v2_1a/exp/xvector_nnet_1a exp
        rm -rf 0008_sitw_v2_1a.tar.gz 0008_sitw_v2_1a
    fi
    # Extract x-vector
    for name in ${train_set} ${dev_set} ${eval_set}; do
        sid/nnet3/xvector/extract_xvectors.sh --cmd "$train_cmd --mem 4G" --nj ${nj} \
            ${nnet_dir} data/${name}_mfcc \
            ${nnet_dir}/xvectors_${name}
    done
    # Update json
    for name in ${train_set} ${dev_set} ${eval_set}; do
        local/update_json.sh ${dumpdir}/${name}/data.json ${nnet_dir}/xvectors_${name}/xvector.scp
    done
```
I wonder if there is any pretained, X-Vector Model, if not, I guess I have to create by myself to apply ASRTTS to JSUT (assuming X-Vector Pretained model is language dependent)

Thank you!

**Comment by kan-bayashi** [comment]
X-vector seems to be language-independent since I used it for `egs/jnas/tts1` (Japanese multi-speaker TTS) and it works well.
Therefore, I think you can use the same model but please be careful x-vector is based on 16k and you should perform resampling.
And in the case of JSUT, since it is a single speaker, x-vector may not be needed if the ASR task is also JSUT.
