### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 539.12 MiB (GPU 0; 1.96 GiB total capacity; 731.36 MiB already allocated; 533.31 MiB free; 90.77 MiB cached)

### ISSUE THREAD

**Issue by craftfortress** [espnet/espnet#1536]
I have 19gb of memory so it is surprising to get this error, which occurs when I increase my example.txt size from one to a few sentences. 

The solution seems to be to decrease the batch_size. 

However I am unsure where in the code I can do this. 

Can I please have a suggestion? Is there a config file? 

I have reported this as an issue because expected results on a GTX 1050 should allow more than one short sentence to be rendered without erroring. This is seems to be a configuration issue.

My example.txt contains 3 sentences.  A four word sentence seems to work fine. 

Thank you for your time.

**Comment by sw005320** [comment]
Which scripts are you using?

**Comment by craftfortress** [comment]
utils/synth_wav.sh example.txt


Should I be using the decoder script instead? If I had an example I would be happy to use that.  I have simple run the above command with a couple of sentences in Upper case. 

Thank you for your time, Im so happy Ive finally got this running ! ( I had to buy a laptop just so I could get this repo to run! )

**Comment by sw005320** [comment]
> utils/synth_wav.sh example.txt
> 
> Should I be using the decoder script instead? If I had an example I would be happy to use that. I have simple run the above command with a couple of sentences in Upper case.

I see.
This should work for short sentences but not for long sentences.
Please use short sentences.
You may also switch to use RNN (ljspeech.tacotron2.v3), then it may make it work (but my recommendation is to use short sentences).

> Thank you for your time, Im so happy Ive finally got this running ! ( I had to buy a laptop just so I could get this repo to run! )

Great to hear that!

**Comment by craftfortress** [comment]
Thank you for your reply I will try it now

**Comment by craftfortress** [comment]
Perhaps my graphics card is not being used correctly. I will look into this now.

**Comment by craftfortress** [comment]
After lots of testing, it seem the program is very happy with around 3 sentences. It performs quickly. About 30 seconds. 

If I do more however, the program hangs until an out of memory exception occurs. 

My question is - is the project meant for just a couple of sentences? 

If so that is ok, I can just feed sentences to it one at a time and then join them together. 

I just wanted to check incase its normal to give it 100 word texts and have it process them without hanging. 

Thank you for your time, great project.

**Comment by sw005320** [comment]
Yes, this is a single sentence based model.

**Comment by Imtinan1996** [comment]
Juts wanted to let you guys know, I am able to synthesize the whole sentence 

"AS YOU SET OUT FOR ITHAKA HOPE YOUR ROAD IS A LONG ONE,FULL OF ADVENTURE FULL OF DISCOVERY. LAISTRYGONIANS, CYCLOPS, ANGRY POSEIDON DONT BE AFRAID OF THEM YOU’LL NEVER FIND THINGS LIKE THAT ON YOUR WAY AS LONG AS YOU KEEP YOUR THOUGHTS RAISED HIGH,AS LONG AS A RARE EXCITEMENT STIRS YOUR SPIRIT AND YOUR BODY. LAISTRYGONIANS CYCLOPS WILD POSEIDON YOU WONT ENCOUNTER THEM UNLESS YOU BRING THEM ALONG INSIDE YOUR SOUL,UNLESS YOUR SOUL SETS THEM UP IN FRONT OF YOU."

on a 12GB GTX 1080Ti (Also the gpu is hosting 4 other models in parallel) as can be seen inthe screenshot below, the process for synthesis is with pid 1808

<img width="886" alt="Screen Shot 2020-01-28 at 10 56 41 AM" src="https://user-images.githubusercontent.com/30050508/73241938-04994780-41bd-11ea-8fec-6cf1e286d871.png">

The problem is definitely not that the sentence is too long. Also just to make things clear, i am NOT using utils/synth_wav.sh and my model was trained on the config train_pytorch_tacotron2.v3

**Comment by sw005320** [comment]
I guess this is because you use tacotron while @craftfortress uses transformer.
