### ISSUE TITLE
Why you apply a guided attention loss to only the two heads of two layers from the target side?

### ISSUE THREAD

**Issue by LEEYOONHYUNG** [espnet/espnet#1538]
Hi, there!

I notice that you apply a guided attention loss to several layers **from the target side.**
However, according to [here](https://arxiv.org/pdf/1809.08895.pdf), it is written that only alignments from certain heads of the **beginning** 2 layers’ are interpretable diagonal lines.

On the contrary, your [paper](https://arxiv.org/pdf/1909.06317.pdf)  is saying that it is because the enc-dec attention matrices are diagonal in only certain heads of a few layers **from the target side** [[4]](https://arxiv.org/pdf/1809.08895.pdf).

Can you check it?

**Comment by unilight** [comment]
Hi @LEEYOONHYUNG , I'm not an official developer of the ESPNet, but I can provide some personal observations. I've tried to train a Transformer-TTS without guided attention (GA) and here's an example of the alignment plot.

![image](https://user-images.githubusercontent.com/11516009/73726621-39843c00-4773-11ea-8ce3-145c7e6b9f0b.png)

As you can see, diagonal alignment lines seems to appear randomly rather than from the lower layers, as reported in the original Transformer-TTS paper. I have also trained Transformer-TTS models with GA and the number of heads showing diagonal lines increased. Nonetheless, I did not rigorously investigate into this. If you are interested in looking into this, I will be curious about your findings! :)

**Comment by kan-bayashi** [comment]
Hi @LEEYOONHYUNG @unilight.
Thank you for interesting report.
I also confirmed the diagonal lines tend to be appeared in 2 or 3 layers from the target side except for the final layer. Actually I’ve never seen the diagonal lines in the beginning layers, differently from the original paper.
