### ISSUE TITLE
voice trembling, in FastSpeech TTS

### ISSUE THREAD

**Issue by EsmaeilFarhang** [espnet/espnet#1557]
Hi,
I'm running Knowledge distillation FastSpeech using train_fastspeech.v4.single.yaml config file for my own language and use char based tacotron2_v3 as a teacher mode, after training the model for 1000 epoch, for the long sentence the voice is trembling. The longer the length of these sentences. The vibration increases.  in this model, The volume of voice is a bit low.
I'm testing Knowledge distillation FastSpeech for ljspeech using pretrained model, and There is also the problem of vibration.
can anyone have knows what is the problem?
Is this problem resolved by continuing model training?

**Comment by kan-bayashi** [comment]
Could you share the samples?
How was the quality of the teacher model?

**Comment by EsmaeilFarhang** [comment]
the quality of the teacher model is a bit better. teacher model trained only 200 epochs.
this is the Persian language
[sample.zip](https://github.com/espnet/espnet/files/4157982/sample.zip)

**Comment by kan-bayashi** [comment]
Thank you for sharing!
In the case of knowledge distillation training, we do not need to prepare the groundtruth of mel-spectrogram since we use generated one as the target of fastpseech. So it is worthwhile to try increasing the training data for fastspeech by using additional text data. According to the authors of FastSpeech, if we can use enough amount of text to generate training data, the FastSpeech will reach the quality of the teacher model.

**Comment by EsmaeilFarhang** [comment]
thank's,
my dataset contains 18702 files and about 22 hours sound. you mean I should increase the size of my dataset and train fastspeech again?, whats about the teacher model? should be continue training?
