### ISSUE TITLE
Move text.cleaner inside espnet.tts

### ISSUE THREAD

**Issue by Fhrozen** [espnet/espnet#1603]
I was testing TTS and following the code from the [guide](https://espnet.github.io/espnet/notebook/tts_realtime_demo.html), however, the part of `from text.cleaners import custom_english_cleaners` give me a little of trouble because I could not find any git related to that, until I looked into [ljspeech dir](https://github.com/espnet/espnet/tree/master/egs/ljspeech/tts1/local/text). This part is required for english, and if ESPnet is imported as a library, this folder need to be added later.
Is it not better to move it as part of espnet.tts.text (?). 
If it is ok, I can then PR this part.

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
That is a nice idea. The problem is that the interface of text cleaning for each language is different. We might want to make a unified text cleaning interface. So I'm wondering just moving `egs/ljspeech/tts1/local/text` is good or not.

**Comment by kamo-naoyuki** [comment]
Related to #1559, I also considered same thing.
I created the following repository for this discussion in advance. https://github.com/espnet/espnet_tts_frontend

This is temporal idea and in addition, I'm not  particular about this structure much.

My intentions to create this repo are:

- It's unclear what modules used for tts recipes. e.g. `g2p_en` because we write all dependencies in setup.py together.
   - I'm really not familiar to tts, so for me, the list of tools is useful.
- The build process of pyopenjtalk is too complex now, so I made the system for pip installation.

My concerning about espnet.tts.text idea:

- `custom_english_cleaners` is originated from the other repository, so I'm not sure whether it's better to include in main repository.
- Text cleaners are used for only in the script level, I mean, now we are not using on-the-fly process for them, so I'd like not to include such tools in main modules as possible (though I also added such modules in `espnet/` in the past... )
- As @kan-bayashi said, we may need to unify the interface. I think it's better to put only such unified interface in `espnet/`.

How do you think? And if this discussion is fixed, I'll implement on the fly feature in espnet2.

**Comment by kan-bayashi** [comment]
> I created the following repository for this discussion in advance. espnet/espnet_tts_frontend

@kamo-naoyuki This is great!

> Text cleaners are used for only in the script level, I mean, now we are not using on-the-fly process for them, so I'd like not to include such tools in main modules as possible

Right. This is one of my reasons why I did not include them under `espnet`.

> As @kan-bayashi said, we may need to unify the interface. I think it's better to put only such unified interface in espnet/.

How about the following example?

```python
class EnglishTextFrontend(TextFrontend):
	def __init__(self, use_phoneme=False)
		pass

	def __call__(self, text):
		"""Clean input text.
		
		Args:
			text (str): English sentence.

		Returns:
			str: Cleaned English sentence.
		
		"""
		pass

class JapaneseTextFrontend(TextFrontend):
	pass
```

The output format should be str or list of str, which is better to use?

**Comment by kamo-naoyuki** [comment]
Now the cleaners was placed in espnet_tts_frontend and it's used now in master #1794
