### ISSUE TITLE
How does wordpiece model decode?

### ISSUE THREAD

**Issue by tu1258** [espnet/espnet#1762]
Sorry if this is a dumb question.

As far as I know, the output layer size is the same as the number of output tokens. Take grapheme model for example, the tokens are a-z and space. Then the output layer weight matrix would be (26+1)*n (n is the output of the previous layer). After the softmax activation, we choose the token with highest value (assume greedy decoding).

If we use 10k wordpiece, then the output layer would be insanely huge (10000*n). It's obvious decoder doesn't work like this. So how does wordpiece model actually work? decoding procedure, output layer size, and etc.

Thanks!

**Comment by xingchensong** [comment]
Also confused about it.

**Comment by ShigekiKarita** [comment]
It is not magic. For exmaple, see the largest model, librispeech 

- The output size is 5000
https://github.com/espnet/espnet/blob/efaf2106cfe976ec4b90de224740518c2416cdb7/egs/librispeech/asr1/run.sh#L55
- The final layer size is 512 (maybe smaller than you expected)
https://github.com/espnet/espnet/blob/efaf2106cfe976ec4b90de224740518c2416cdb7/egs/librispeech/asr1/conf/tuning/train_pytorch_transformer_large_ngpu4.yaml#L3
- The beam size in decoding is 60
https://github.com/espnet/espnet/blob/efaf2106cfe976ec4b90de224740518c2416cdb7/egs/librispeech/asr1/conf/tuning/decode_pytorch_transformer_large.yaml#L2

As you imagined, it requires `5000 * 512 * 4 bytes = 10M bytes` for the np.float32 (4 bytes) weight before softmax output per prefix decoding iteration.  And we can ignore the beam size: 60 because we do not conduct parallel decoding usually (we use for loop).

**Comment by tu1258** [comment]
So we don't need to increase decoding layer, we just use a linear projection to project from (n_hidden) to (# of output tokens)? Correct me if I am wrong, thanks!
