### ISSUE TITLE
Parallel WaveGAN settings

### ISSUE THREAD

**Issue by qo4on** [espnet/espnet#1827]
I have very strange [sound artifacts](https://dl.dropboxusercontent.com/s/9nvab95nbcnq05g/test_pwg.wav) with Parallel WaveGAN (with FastSpeach in Colab example). Listen how "for awhile` sounds.
1. Is there something I can tune in inference to fix that?
2. Also I found that sound is a little better when I feed several sentences at once instead of just one. Which is the best approach with Parallel WaveGAN?

**Comment by kan-bayashi** [comment]
1. In the inference, we use random noise. So if you perform the generation again, the outputs will be a little bit changed but not so large.

2. Not sure. It depends on the Text2Mel part, I think. From your results, the FastSpeech model may be able to generate Mel well with a long sentence since it can consider the context in the long sentence (?). 

Currently, we separately trained Text2Mel and Mel2Wav. But if we train Mel2Wav with groundtruth aligned outputs, the quality may be improved since the mismatch of the feature is reduced.
