### ISSUE TITLE
Question about Fastspeech transfer learning

### ISSUE THREAD

**Issue by machineko** [espnet/espnet#1837]
Did anyone ever try to do transfer learning without teacher model on fastspeech?
In normal traning we need taco2 or transformer as teacher but what about transfer learning on new dataset did anyone have experience with it?

**Comment by kan-bayashi** [comment]
If we perform forward propagation without groundtruth alignment (basically calculated by the teacher model), the length of outputs will be different from groundtruth since it is predicted by the duration predictor. Therefore, the transfer learning or fine-tuning of FastSpeech is not straightforward.
