### ISSUE TITLE
why not support espnet pip install directly, but to git clone, pip?

### ISSUE THREAD

**Issue by Pydataman** [espnet/espnet#1852]

**Comment by sw005320** [comment]
We initially have some complicated dependencies that come from Kaldi and warp CTC. We can use built-in pytorch CTC and espnet2 is Kaldi-free. So, we could make it. But the warp transducer would be an issue.

**Comment by kamo-naoyuki** [comment]
Although some additional installations are inevitable for the full experiment, the pip installation for the restricted packages might be convenient for some use cases.

On the other hand,  I'm not sure whether it's meaningfull to distribute from pypi server because there are no big difference from the current way:

```bash
pip install espnet  # If register to pypi
pip install git+https://github.com/espnet/espnet  # Current
```

To be honest, our versioning policy is ambiguous and we couldn't schedule the development strictly because espnet was developed by a few researchers mainly, so I hesitated to register espnet to pypi server.

**Comment by Pydataman** [comment]
> Although some additional installations are inevitable for the full experiment, the pip installation for the restricted packages might be convenient for some use cases.
> 
> On the other hand, I'm not sure whether it's meaningfull to distribute from pypi server because there are no big difference from the current way:
> 
> ```shell
> pip install espnet  # If register to pypi
> pip install git+https://github.com/espnet/espnet  # Current
> ```
> 
> To be honest, our versioning policy is ambiguous and we couldn't schedule the development strictly because espnet was developed by a few researchers mainly, so I hesitated to register espnet to pypi server.

but for deployment, it is convenient.

**Comment by kamo-naoyuki** [comment]
> but for deployment, it is convenient.

If you wonder only for deployment, you can use the following syntax instead.

```Python
# Using git
setup.py(
    ...
    install_requires=["espnet@git+https://github.com/espnet/espnet.git@v.0.6.3"]
)

# Using zip
setup.py(
    ...
    install_requires=["espnet@https://github.com/espnet/espnet/archive/v.0.6.3.zip"]
)
```

Having said that it's better to register to pypi server because pypi server guarantees the existence and identity of the package strictly, while the github assets can be removed/changed.

**Comment by kamo-naoyuki** [comment]
I registered espnet to pypi.
