### ISSUE TITLE
Model selection criteria for TTS

### ISSUE THREAD

**Issue by sharathadavanne** [espnet/espnet#1892]
Hello, this is not really about an issue of ESPnet. But a thread to discuss the different **quantitative model selection criteria** to choose the best model from different epochs of training. One obvious choice is to select the model that has the least loss (L2 + attention etc.) on validation data. However, this may not always correspond to the most natural and intelligible TTS model. Another way is to choose the model by using ASR based WER on the validation data and select the model from the epoch with the best WER. This approach might choose the model with the highest intelligibility, however, it might be expensive to compute it at each epoch. In this regard, I wanted to gather what are the other approaches people have been using for their model selection?

**Comment by sw005320** [comment]
Thanks for raising an interesting issue.
Another possibility is to check the attention weights but this becomes complicated for transformer because we have a lot of attention weights (self/source-target, each layer, each head).
We have a related issue in #1665 
We can implement some metrics during training, as well for model selection.

@kan-bayashi and @unilight, maybe it's time to work on it (after the Interspeech deadline)?
