### ISSUE TITLE
Modularization

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#195]
@hirofumi0810 pointed out that it would be better to modularize the network part (say split it to encoder, decoder, and attention parts). I want to ask your opinions about this direction.

**Comment by kan-bayashi** [comment]
I agree this idea. 
`e2e_asr_attctc` and `e2e_asr_attctc_th` became bigger and difficult to maintain.
Separating each modules makes it easy to develop them.

**Comment by takaaki-hori** [comment]
Considering future extension of e2e models, it would be better to split it into encoder, decoder, and attention parts so that we can easily add new modules and combine them accordingly.
For example, this kind of instantiation may be possible.

 e2e = E2E(encoder=VGGBLSTMP(...), decoder=LSTMDecoder(...), attention=MultiHeadAttention(...))

I am not sure this is the best way, but we will be able to let each module have consistent interface.

**Comment by sw005320** [comment]
Thanks fo your comments.
I tend to agree with modularization.
My concerns are as follows:

- one file is easy to edit (thousand lines are still OK level for me)
- I'm not sure that we can completely fix encoder/decoder/attention interfaces

**Comment by pozhijisi** [comment]
Instead of using shared interfaces (which seems to be hard to design), what about placing combinations of (encoder, decoder, attention) into different folders?

For example, we may create different folders for (VGGBLSTMP, LSTM, MultiHeadAttention), (VGGBLSTMP, LSTM, Location), etc. Each folder can work independently.

Although this method may create many redundant files, it is like using a list data structure to store all the possible combinations. With the flexibility of this method, we may attract more contributors pushing their own design into the repository and expanding our community at a higher pace.
