### ISSUE TITLE
ngram scorer issues

### ISSUE THREAD

**Issue by Cescfangs** [espnet/espnet#1974]
Please correct me if I'm wrong, I think we're scoring `p(yn|y0~yn-1)` here, however following code score `p(y0~yn)` actually:
https://github.com/espnet/espnet/blob/263e3c61a7732002e5e5b49a9c510ecc02f5c329/espnet/nets/scorers/ngram.py#L56-L61
I suggest:
```python
        for i, j in enumerate(next_token):
            scores[i] = self.lm.BaseScore(
                out_state, self.chardict[j], self.tmpkenlmstate
            )
```
and below is my decoding result with Aishell(the model was trained with other mandarin dataset, and the ngram lm was trained with much larger corpus):

| Aishell test                 | CER  |  weight   |
| ---------------------------- | ---- | ---- |
| baseline                     | 6.8% |  0    |
| +ngram part scorer(origin)        | 7.2% |  0.1  |
| +ngram part scorer(my suggestion) | 6.3% |  0.1  |
| +ngram part scorer(my suggestion) | 5.6% |  0.3  |
| +ngram part scorer(my suggestion) | 5.1% |  0.5  |
| +ngram part scorer(my suggestion) | 4.7% |  0.7  |
| +ngram part scorer(my suggestion) | 4.4% |  0.9  |

Another issue is the `NgramFullScorer`, which is too slow for large vocab like chinese:
https://github.com/espnet/espnet/blob/263e3c61a7732002e5e5b49a9c510ecc02f5c329/espnet/asr/pytorch_backend/recog.py#L68-L71
here is my results:
| 20 utt       | decoding time |
| ------------ | ------------- |
| baseline     | 280 s         |
| +full scorer | 975 s         |
| +part scorer | 358 s         |

So I would like to suggest using ngram part scorer for decoding:
```python
if args.ngram_model:
    from espnet.nets.pytorch_backend.scorers.ngram import NgramPartScorer 
 
    ngram = NgramPartScorer(args.ngram_model, train_args.char_list) 
```

**Comment by sw005320** [comment]
Wow!
This is super cool.
Thanks for pointing out.

@qmpzzpmq, could you fix it accordingly?
#1946

**Comment by qmpzzpmq** [comment]
@Cescfangs 
and for the first point, my personal understanding is, the last decoding already decoded the score p
I read the example in https://github.com/kpu/kenlm/blob/87e85e66c99ceff1fab2500a7c60c01da7315eec/python/example.py#L37-L38
For example, currently, if the ngram would be score p(y_{n}|y_{0}~y{n-1}), which could be augmented as p(y_{n}|y_{0}~y{n-1})=p(y_{n}|y_{n-1})*p(y_{n-1}|y_{0}~y{n-2}), and this p(y_{n-1}|y_{0}~y{n-2}) could be getted from the last decoding named state[1]. 
But I think your suggestion looks like 1 gram. The result loos better might since the testset in aishell is quite short.

yes, I already implement the NgramPartScorer as an option in recog.py
https://github.com/qmpzzpmq/espnet/blob/627926b54ac2c134c7bc8517855689e66bd766e5/espnet/bin/asr_recog.py#L177-L183

**Comment by Cescfangs** [comment]
> @Cescfangs
> and for the first point, my personal understanding is, the last decoding already decoded the score p
> I read the example in https://github.com/kpu/kenlm/blob/87e85e66c99ceff1fab2500a7c60c01da7315eec/python/example.py#L37-L38
> For example, currently, if the ngram would be score p(y_{n}|y_{0}~y{n-1}), which could be augmented as p(y_{n}|y_{0}~y{n-1})=p(y_{n}|y_{n-1})*p(y_{n-1}|y_{0}~y{n-2}), and this p(y_{n-1}|y_{0}~y{n-2}) could be getted from the last decoding named state[1].
> But I think your suggestion looks like 1 gram. The result loos better might since the testset in aishell is quite short.
> 
> yes, I already implement the NgramPartScorer as an option in recog.py
> https://github.com/qmpzzpmq/espnet/blob/627926b54ac2c134c7bc8517855689e66bd766e5/espnet/bin/asr_recog.py#L177-L183

Thanks for the explanation, first of all, I tested several datasets including long conversations, the conclusions were quite similar.
I agree the state[1] represents p(yn-1|y0...yn-2), but I think you made a mistake about `BaseScore()`, it's actually a incremental scoring method, which means it scores p(yn|y0...yn-1) instead of p(yn|yn-1)(state make this happen).
The example in kenlm verified my opinion indeed, if `BaseScore` is scoring p(yn|yn-1) how could the accumulated one equals the sentence score? 
here is a small experiment about `BaseScore`:
![score](https://user-images.githubusercontent.com/11382612/83105860-07b22f00-a0ee-11ea-833d-98f7a8ac3186.PNG)
as you can see the scores are different because of the context

**Comment by qmpzzpmq** [comment]
I don't understand you mean of "verified".
Since in the example https://github.com/kpu/kenlm/blob/87e85e66c99ceff1fab2500a7c60c01da7315eec/python/example.py#L41
the score of "<s> a sentence" actually is accumulated from the score of p("a"|<s>)  and p("sentence"|"a")/
and the score of "<s> a sentence </s>" is same, https://github.com/kpu/kenlm/blob/87e85e66c99ceff1fab2500a7c60c01da7315eec/python/example.py#L43
the reason of difference in your pic. the first "-1.58" is the score p(“是”|"我") it might computed from p("是"|"<s> 我")/p("我"|"<s>"), if the 3gram "<s> 我是" exists.
Same,  the scond score -0.58 p(“是”|"我") it might computed from p("是"|"是 我")/p("我"|"<s>"), if the 3gram "我 我 是" exists.
And there is another thing. If there is no state variable. p(y_{n}|y_{0}~y{n-1})=p(y_{n}|y_{n-1})*p(y_{n-1}|y_{0}~y{n-2}), is totally the chain role, which means these chain role totally rely on the 1gram.
p(y_{n}|y_{0}~y{n-1}) = \prod_{i=0}^{n-1} p(i+1|i). Since the state, Basescore might use large ngram.

**Comment by qmpzzpmq** [comment]
@Cescfangs 
p(<s> 银行 放贷 行为 </s>)=p(银行|<s>)p(放贷|<s> 银行)p(行为|银行 放贷)p(</s>|放贷 行为)

**Comment by Cescfangs** [comment]
@qmpzzpmq thanks for the replay, I re-checked about the `BaseScore`, and I think you're right about the ngram state:
```python
model.BaseScore(state2, '我', state)
model.BaseScore(state, '是', state2)
model.BaseScore(state2, '我', state)
model.BaseScore(state, '是', state2)
model.BaseScore(state2, '我', state)
model.BaseScore(state, '是', state2)
model.BaseScore(state2, '我', state)
model.BaseScore(state, '是', state2)

 -0.58933...
```
So it's actually a **ngram** incremental scoring method

**Comment by Cescfangs** [comment]
@qmpzzpmq Ok, I made a mistake, for RNNLM, we're scoring p(yn|y0...yn-1), but for ngram lm, we are scoring p(yn|yn-3,yn-2,yn-1), right? If so I think we don't need to accumulate ngram scores either, it's the limitation of ngram lm, but I think this is how it works.

**Comment by qmpzzpmq** [comment]
@Cescfangs. I will talk with @sw005320 later to choose an appropriate one, big thanks for your result.
