### ISSUE TITLE
trainconf-help

### ISSUE THREAD

**Issue by 943274923** [espnet/espnet#2015]
I use "conf/tuning/train_pytorch_transformer_large_ngpu4.yaml "to train Librispeech ,when I use 4 GPUs ,it need 7days .but I use ngpus=8,the train time  about 9 days. why I use more GPU but the train time increases .how should I change train_pytorch_transformer_large_ngpu4.yaml for 8gpus.Thanks

**Comment by kamo-naoyuki** [comment]
Multi gpus training ifself has some overheads due to gpu-gpu communication and pytorch's data parallel is also inefficient implementation because it depends on python-threading. It suffers the problem of global-interpreter-lock. Thus speed degradation is reasonable, if you are using same mini-batch size.

ESPnet2 supports distributed data parallel for one node (= multi gpus with multi processing). It's faster than  espnet1's implementation.

**Comment by BuaaAlban** [comment]
> I use "conf/tuning/train_pytorch_transformer_large_ngpu4.yaml "to train Librispeech ,when I use 4 GPUs ,it need 7days .but I use ngpus=8,the train time about 9 days. why I use more GPU but the train time increases .how should I change train_pytorch_transformer_large_ngpu4.yaml for 8gpus.Thanks

I also need 7 days to train 120 epoch using 4 gpus, but it seems it converge with a ok result in one day.
