### ISSUE TITLE
Using an4 ASR recipe on new WAV file

### ISSUE THREAD

**Issue by seanle24245** [espnet/espnet#2096]
I am following the an4 speech recognition recipe.  I ran run.sh and now have a trained model.  I have tested the ASR on different examples by changing the number 10 in the following code, which refers to the 10th speech in data.json, which is in dump/test/deltafalse:

`key, info = list(test_json.items())[10]`

If I want to use this an4 model to decode a WAV file I have, how would I go about doing that?  Is there a straightforward way to feed it my own file?  Where exactly should I be adding new test information?  My best guess is I have to convert it into an .sph file first, make a folder for it in `/espnet/egs/an4/asr1/downloads/an4/wav/an4test_clstk/` but I have no idea.  Then maybe re run some portion of run.sh to process everything for the /dump directory?

I'm very new to this so if my question does not make sense I apologize!

**Comment by sw005320** [comment]
I think you can follow https://github.com/espnet/espnet/blob/master/utils/recog_wav.sh
If you want to use your trained an4 model, you can specify your model and other related files instead of pre-trained models in the above shell script.

Note that an4 is used to test whether our program is working well since it is based on a very small amount of training data. So, the performance of an4 trained models is poor and it would not well recognizer a WAV file you have.
