### ISSUE TITLE
copy-feats: command not found

### ISSUE THREAD

**Issue by mlxu995** [espnet/espnet#2116]
I try to run eg2/aishell/asr1/run.sh and it seems I should compile Kaldi first?
the bug is :
      bash: line 1: copy-feats: command not found
      bash: line 1: paste-feats: command not found
How can I run it without compiling Kaldi?

**Comment by kamo-naoyuki** [comment]
Aishell recipe now uses feats_type=fbank_pitch. 
It should be feats_type=raw, but pitch feats may give good performance for Mandarin speech @sw005320 ?

You can run without Kaldi as follows

```bash
./run.sh --feats_type=raw
```

**Comment by sw005320** [comment]
> Aishell recipe now uses feats_type=fbank_pitch.
> It should be feats_type=raw, but pitch feats may give good performance for Mandarin speech @sw005320 ?
> 

Yes, the effectiveness of the pitch feature for Mandarin was significant (e.g., relative 10% improvement in HKUST in our old trial in 2016).

By considering the Kaldi-free policy, unifying the feature extraction setup for multilingual ASR, and the computational graph point of view, it would be better to use the default `—feat_type=raw` mode in the future, even for the Mandarin task. Now, the ASR e2e model becomes very strong and I believe the difference due to the feature can be mitigated.
