### ISSUE TITLE
StreamingTransformer

### ISSUE THREAD

**Issue by qmpzzpmq** [espnet/espnet#2173]
is possible to merge this repo's work into espnet
https://github.com/cywang97/StreamingTransformer

**Comment by sw005320** [comment]
Many thanks.
This looks very interesting.
I'm thinking of implementing some streaming ASR in the near future with espnet2.
@hirofumi0810 has a very good technique https://arxiv.org/pdf/2005.04712.pdf https://arxiv.org/pdf/2005.09394.pdf and he is planning to implement it in espnet2
Sony and I also have some recent efforts of streaming ASR https://arxiv.org/pdf/2006.14941.pdf
This is also based on espnet and is simple and effective.
We're planning to implement it in espnet2

Overall, I'm quite keen to implement a streaming transformer in the near future, probably this fall.
Like the implementation policy of the other parts, we'll try to provide several streaming options including the method you mentioned as an option instead of one method.
@b-flo is also working on a streaming transducer.

So, please stay tuned, and we may need your help again then ;)
