### ISSUE TITLE
Small dataset inference issue

### ISSUE THREAD

**Issue by gafsd** [espnet/espnet#2309]
I am still having issues with small datasets where inference starts out ok then mumbles after a second or so - now I wonder whether pretrained model male vs female make a difference (I have been trying with pretrained female ljspeech model for male dataset). What do you think?

**Comment by kan-bayashi** [comment]
Since I have no good male dataset, I have no clear answer.
In my experiences, adaptation with a female model + small male dataset works well.
But if you can prepare the good single male model, it is better to use it as the initial model.
Also, in the case of adaptation, it is better to clean the dataset as much as possible.
(Remove silence, add symbols corresponding to the pause, etc...)
