### ISSUE TITLE
Unable to set batch_size in tts training

### ISSUE THREAD

**Issue by Piteryo** [espnet/espnet#2375]
There is no such option in tts.sh (script fails if you try to pass it) and setting it in train.yaml also does nothing - it is always 20.

**Comment by kan-bayashi** [comment]
See https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type
There are several mini-batch type.
In the following config, we use `batch_type=numel` and specify `batch_bins` instead of `batch_size` to enable us to use dynamic batch size. 
https://github.com/espnet/espnet/blob/96b2fd08d4fd9276aabd7ad41ec5e02a88b30958/egs2/ljspeech/tts1/conf/tuning/train_tacotron2.yaml#L61-L62

**Comment by Piteryo** [comment]
> See https://espnet.github.io/espnet/espnet2_training_option.html#change-mini-batch-type
> There are several mini-batch type.
> In the following config, we use `batch_type=numel` and specify `batch_bins` instead of `batch_size` to enable us to use dynamic batch size.
> https://github.com/espnet/espnet/blob/96b2fd08d4fd9276aabd7ad41ec5e02a88b30958/egs2/ljspeech/tts1/conf/tuning/train_tacotron2.yaml#L61-L62

it was unclear from the docs I read, thanks!

**Comment by kan-bayashi** [comment]
Updated README https://github.com/espnet/espnet/pull/2376
