### ISSUE TITLE
Data augmentation : problem when I try to use perturb_data_dir_speed.sh

### ISSUE THREAD

**Issue by amejri** [espnet/espnet#2395]
Hello guys, 

When I try to speed up commonvoice audio files by using perturb_data_dir_speed.sh file, I encounter the following problem:
ERROR (wav-to-duration[5.5.735~1-7ef20]:main():wav-to-duration.cc:80) Error: member 001b79ad83c8bb7c5591f059b31611157620e20f647eab28720c1dc40baac089bc9d1551e0ea5e0e4bdef30a97afdbb7a1f2e6d325deab3434b9848c0ad95f1e-common_voice_fr_17314979 has no duration in header. Check the source, and/or try --read-entire-file.

I add it in run.sh as follow : 

    # # Code     
    if [ ${stage} -le 1 ] && [ ${stop_stage} -ge 1 ]; then
    ### Task dependent. You have to design training and dev sets by yourself.
    ### But you can utilize Kaldi recipes in most cases
    echo "stage 1: Feature Generation"

    # # speed purturbation
    cp -r data/${train_set} data/${train_set_dup}
    utils/perturb_data_dir_speed.sh 0.8 data/${train_set_dup} data/temp1
    utils/perturb_data_dir_speed.sh 1.0 data/${train_set_dup} data/temp2
    utils/perturb_data_dir_speed.sh 1.2 data/${train_set_dup} data/temp3
    utils/combine_data.sh --extra-files utt2uniq data/${train_set} data/temp1 data/temp2 data/temp3
    rm -r data/temp1 data/temp2 data/temp3

    fbankdir=fbank
    # Generate the fbank features; by default 80-dimensional fbanks with pitch on each frame
    for x in ${train_set} ${train_dev} ${recog_set}; do
        steps/make_fbank_pitch.sh --cmd "$train_cmd" --nj 4 --write_utt2num_frames true \
                                  data/${x} exp/make_fbank/${x} ${fbankdir}
        utils/fix_data_dir.sh data/${x}
    done

have anyone encountred this problem yet ?
Thanks,

**Comment by kamo-naoyuki** [comment]
This is well known error in audio processing and not related to perturb_data_dir_speed.sh, but the problem of your audio file.

Wav file has some information at its header, duration, channel number, sampling frequency, etc. Sometimes, wav file doesn't have duration information, e.g. by online recoding,  originally, it can't give duration information at header, but it generates a wav file somehow with the incomplete header.

Audio converter, such as sox, ffmpeg, can handle such incomplete audio files, but kaldi's `wav-to-duration` can't handle it because it relies on the header information to derive the duration. This is not fault of Kaldi. 

Probably, you can solve the problem if  `--read-entire-file` option to  `wav-to-duration`  command as your error log said. (but I have never used the option.)

Another solution is recreating new audio file using some tools.

```sh
sox in.wav out.wav
```

Sox gives correct duration at the header, in my memory, maybe.

**Comment by v-yunbin** [comment]
whether  the act of making fbank before perturbing the training data is **redundant** ?
The later steps do not need  the training features with nopitch
