### ISSUE TITLE
Transformer TTS decoder: output dimension set to -1

### ISSUE THREAD

**Issue by ElinaBaral** [espnet/espnet#2454]
I am trying to build speech autoencoder from Transformer TTS by making it independent of character (also removing Encoder-prenet)
But in the Transformer TTS decoder the odim is set to -1 (https://github.com/espnet/espnet/blob/master/espnet/nets/pytorch_backend/e2e_tts_transformer.py line 619) which raises the error "Trying to create tensor with negative dimension -1". 
When setting odim=odim raises the error "Tried to access index -1 out of table with 79 rows".

I looked into other TTS code of Espnet (also in espnet2's transformer TTS) they haven't used -1 as output dimension.

**Comment by kan-bayashi** [comment]
Due to the compatibility for the ASR model, we use use_output_layer=False.
https://github.com/espnet/espnet/blob/009d543025c59354aa40a3abb898a33154e482c8/espnet/nets/pytorch_backend/e2e_tts_transformer.py#L629
In this case, odim is not used, so -1 will be valid argument.
https://github.com/espnet/espnet/blob/009d543025c59354aa40a3abb898a33154e482c8/espnet/nets/pytorch_backend/transformer/decoder.py#L233-L236

**Comment by kan-bayashi** [comment]
If you have further questions, please re-open.
