### ISSUE TITLE
to experiment with content-based attention

### ISSUE THREAD

**Issue by shubham-IISc** [espnet/espnet#255]
I wanted to observe the impact of convolutional features(improvements) implemented through location based attention in toolkit. 
so, I tried with aconv-chans=0 and aconv-flts=0 (assumed that it will remove convolutional features) but that gives an error.
Is there anyway to experiment only with content based attention(without convolutional features)?
Thanks

**Comment by sw005320** [comment]
We don't implement this due to our previous investigations, and if you want to do it, you can simply hack the corresponding lines as follows: 
```
        e = linear_tensor(self.gvec, torch.tanh(
            att_conv + self.pre_compute_enc_h + dec_z_tiled)).squeeze(2)
```
->
```
        e = linear_tensor(self.gvec, torch.tanh(
            self.pre_compute_enc_h + dec_z_tiled)).squeeze(2)
```
in the PyTorch backend https://github.com/espnet/espnet/blob/master/src/nets/e2e_asr_attctc_th.py#L762 or 
```
        e = F.squeeze(linear_tensor(self.gvec, F.tanh(
            att_conv + self.pre_compute_enc_h + dec_z_tiled)), axis=2)
```
->
```
        e = F.squeeze(linear_tensor(self.gvec, F.tanh(
            self.pre_compute_enc_h + dec_z_tiled)), axis=2)
```
in the Chainer backend https://github.com/espnet/espnet/blob/master/src/nets/e2e_asr_attctc.py#L506

**Comment by shubham-IISc** [comment]
thanks.. it worked.
