### ISSUE TITLE
transformer decode for long audio or short audio

### ISSUE THREAD

**Issue by shunfeichen** [espnet/espnet#2608]
Hi,
     I train a transformer model using the scripte of Aishell-1. The results of the test and dev is reasonable, but when  I decoding my own test set, the results become very bad . I have two test set , the one is long audio about news and the other is short audio only including two or three Chinese  characters. So  I want to konw , is there any solution to solve the problem ?

Thank you ,very much.

**Comment by sw005320** [comment]
We have two solutions
1. cut the audio with external VAD tools, e.g., https://github.com/wiseman/py-webrtcvad
2. use the relative positional encoding with a huge memory machine

I recommend the first option.
The second option does not completely solve the problem since the transformer requires a huge memory for long audio.

**Comment by shunfeichen** [comment]
> We have two solutions
> 
> 1. cut the audio with external VAD tools, e.g., https://github.com/wiseman/py-webrtcvad
> 2. use the relative positional encoding with a huge memory machine
> 
> I recommend the first option.
> The second option does not completely solve the problem since the transformer requires a huge memory for long audio.

Thank you very much , I will try. By the way, as the short  audio， how can I solve the problem？

**Comment by shunfeichen** [comment]
> IMO this is the best practical/pragmatic basis currently available for segmentation, especially if you are looking at processing longform audio offline. You can combine it with webrtcvad to further smooth the segments. The approach is particularly useful if you deal with files containing mixtures of music/speech/noise/long silences.
> 
> * https://github.com/ina-foss/inaSpeechSegmenter

Thank you very much.

**Comment by keshawnhsieh** [comment]
I came across these same situations recently. See issues [here](https://github.com/espnet/espnet/issues/2893) and [here](https://github.com/espnet/espnet/issues/2797). By the way, I got such similar performance degradation under conformer model.

I am suspecting that the degradation is caused by some unknown bug in espnet during decoding rather than model itself?

Any updates since then you found this problem. Discussion welcomed and thank you!
