### ISSUE TITLE
Training librispeech model on small part of dataset - train-clean-100 

### ISSUE THREAD

**Issue by anjadia** [espnet/espnet#2657]
Hi, I tried to train librispeech model only on `dev-clean test-clean dev-other test-other train-clean-100` (model GPU Quadro RTX 5000) with default config with one exception: 
`train_lm_adam.yaml`:
```lm_conf:
    nlayers: 4
    unit: 2048
optim: adam
optim_conf:
    lr: 0.001
batch_type: folded
batch_size: 100   # batch size in LM training
max_epoch: 20     # if the data size is large, we can reduce this
patience: 3

best_model_criterion:
-   - valid
    - loss
    - min
keep_nbest_models: 1
```

But training takes longer than it should. After 4 days, not even the 3rd epoch has passed. In the attachment I added training logs. Why does it take so long? 
[train.log](https://github.com/espnet/espnet/files/5509960/train.log)

**Comment by sw005320** [comment]
The model size of librispeech LM and text data are relatively large, and it may take very long time.
I think one epoch per day seems to be normal.

**Comment by kwasnydam** [comment]
Thanks, in that case, feel free to close the issue. The answer here kinda suggested otherwise (https://github.com/espnet/espnet/issues/509#issuecomment-449026082) and we thought it was also referring to one GPU scenario. Is there maybe the RNNLM for librispeech part available in the model zoo, so we could skip this part for now and just put the model in the expected place?

**Comment by sw005320** [comment]
Yes you can find it at https://zenodo.org/record/3966501

**Comment by panpanli521** [comment]
hello,  have you trained librispeech model on multiple GPUs with multiprocessing_distributed mode?   @anjadia
