### ISSUE TITLE
Is it easy to implement Distributed training on espent 1?

### ISSUE THREAD

**Issue by WanderingSven** [espnet/espnet#2658]
hello everyone.
        Because my many code use espnet 1, the Data parallel is slow on it. If I want to implement distributed training by pytorch, is it easy to implemnt? And can I continue to use chainer.?

**Comment by sw005320** [comment]
Is it not easy to implement distributed training on espnet1, but I heard someone successfully made it.
We'd not officially support it, but instead, I recommend you to port your code on espnet2. 
If you have encountered the slow training in data-parallel, it would not be solved if you just simply use distributed training because the slow training may be due to various reasons. I recommend you to check https://espnet.github.io/espnet/tutorial.html#multiple-gpu-tips

**Comment by kamo-naoyuki** [comment]
If you are enough familiar both with pytorch distributed parallel and espnet1, it's not impossible to hack it in some times. I just only introduce main modifications that you may need:

- DataParallel -> DistributedDataParallel: https://github.com/espnet/espnet/blob/afdeff8bb236732292649ff423504f4cb678c47f/espnet/asr/pytorch_backend/asr.py#L201-L208
- Split mini batch for each processes: https://github.com/espnet/espnet/blob/9c55468b96bdb2d45acd08ee52bf154bd4518e5a/espnet/asr/pytorch_backend/asr.py#L564

You need to modify many small things other than them.

**Comment by WanderingSven** [comment]
Thank you guys for reply @sw005320 @kamo-naoyuki
