### ISSUE TITLE
--init_param option error?

### ISSUE THREAD

**Issue by abnerLing** [espnet/espnet#2760]
I'm trying to fine tune a new dataset using a pretrained model but I get some error which I don't understand.
All I did so far was included the init parameter in the training config file and I get the below error.  Thank you.
init_param:
 - /data/mode.pth

RuntimeError: Error(s) in loading state_dict for ESPnetASRModel:
        Unexpected key(s) in state_dict: "normalize.mean", "normalize.std".

**Comment by kamo-naoyuki** [comment]
Please describe more information. 

I guess you are using utterance_mvn, which doesn't have instead of global_mvn.

**Comment by abnerLing** [comment]
So I have a pretrained model using 900+ hours of data, and I wanted to finetune that model with an outside dataset of 50 hours using all parameters. When including init_param in the training config an error appears at stage 9 during ASR stats collection. The model I pretrained used global_mvn. 



[RTX1] 2020-12-08 02:53:42,462 (abs_task:1132) INFO: Saving the configuration in exp/asr_stats_raw_bpe5000/logdir/stats.1/config.yaml
[RTX1] 2020-12-08 02:53:42,684 (abs_task:1138) INFO: Loading pretrained params from /data/abner/espnet/egs2/kspon/asr/exp/asr_train_asr_conformer_raw_bpe5000/valid.acc.ave_10best.pth
Traceback (most recent call last):
  File "/root/anaconda3/envs/es/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/es/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/abner/espnet/espnet2/bin/asr_train.py", line 23, in <module>
    main()
  File "/data/abner/espnet/espnet2/bin/asr_train.py", line 19, in main
    ASRTask.main(cmd=cmd)
  File "/data/abner/espnet/espnet2/tasks/abs_task.py", line 990, in main
    cls.main_worker(args)
  File "/data/abner/espnet/espnet2/tasks/abs_task.py", line 1146, in main_worker
    else "cpu",
  File "/data/abner/espnet/espnet2/torch_utils/load_pretrained_model.py", line 81, in load_pretrained_model
    obj.load_state_dict(dst_state)
  File "/root/anaconda3/envs/es/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ESPnetASRModel:
        Unexpected key(s) in state_dict: "normalize.mean", "normalize.std".
[RTX1] 2020-12-08 02:53:43,053 (internal:138) INFO: Internal process exited
# Accounting: time=9 threads=1
# Ended (code 1) at Tue Dec  8 02:53:44 EST 2020, elapsed time 9 seconds

**Comment by kamo-naoyuki** [comment]
I got it. This is a little bit complicated.

The default normalize is utterance_mvn and utterance_mvn is actually specified for collect stats stage.  I mean:

-  Collect stats  -> utterance_mvn (because we don't have stats files yet)
- Training -> global mvn (this configuration is given at shell level)

However, you are giving pretrained model for collect stats stage, because that is written in your configuration file and it's also given in collect stats mode, thus it show the error.

- Workaround1

You don't need to give configuration file at collect stats mode in this case


```
./run.sh --stage 9 --stop-stage 9
./run.sh --asr_config ... --stage 10
```

- Workaround2: Specify global_mvn in your configuration file.
- Workaround3: The parameters of global mnv is meaningless because they are overwritten by given stats file, so you can exclude them. 

```
--init_param model.pth:::normalize
```

**Comment by abnerLing** [comment]
Thank you very much, its working fine now!
