### ISSUE TITLE
There is a distinct pause in the words： csmsc model

### ISSUE THREAD

**Issue by wac81** [espnet/espnet#2849]
There is a distinct pause in the words： csmsc model

ex:
国家重要战略项目--->国家（重|要<---- Unsuitable pause)  战略项目

how to fix it?

**Comment by kan-bayashi** [comment]
Which model did you use? (transformer, tacotron2, fastspeech, etc.)

**Comment by wac81** [comment]
fastspeech2-conformer

**Comment by wac81** [comment]
error audio:
https://drive.google.com/file/d/1T_V4kebZTOOIIBguEnpfT57aiDQO9uGb/view?usp=sharing

**Comment by kan-bayashi** [comment]
Since I could not understand Mandarin, I could not understand the what is a problem.
It sounds normal for me, it is difficult to control in detail.
Maybe the pronunciation will be improved when you use a long input (国家重要战略项目 + alpha?)

**Comment by wac81** [comment]
重要 is a word ， means important,   there is a problem like sound 'import' and 'ant' split。

**Comment by ly1984** [comment]
@kan-bayashi because Mandarin is character bases, the model did not get the right prosody, for example, the pronunciation  of  "Monday" sound like "Mon" long pause "day".

@wac81 you need to re-train the fastspeech2-conformer model.
two methods to solve this problem
1：
1) change #1 #2 #3 #4 to # in data.sh
2)modify pypinyin_g2p_phone in phoneme_tokenizer.py to accept # as a token
3)when synthesis, use jieba to add # after each word.

2:
1)keep #1 #2 #3 #4 in data.sh
2)modify pypinyin_g2p_phone in phoneme_tokenizer.py to accept #1 #2 #3 #4  as a token
3)when synthesis,use a prosody model to generate #1 #2 #3

**Comment by wac81** [comment]
This only happens in some cases，same word in sentences is different interword pause，some of the normal

#1 #2 #3 #4 can fix some of situation， but for new sentence Is it still in effect？

**Comment by ly1984** [comment]
> thanks for your answer
> 
> This only happens in some cases，same word in sentences is different interword pause，some of the normal
> 
> method one：
> 
> 1. #1 #2 #3 #4 can fix some of situation， but for new sentence Is it still in effect？
> 2. 3)when synthesis, use jieba to add # after each word.
>    -----jieba just for each word, but sometimes # split the phrase
> 
> method two:
> which prosody model? how to train that? this method looks reliable

https://github.com/Zeqiang-Lai/Prosody_Prediction

**Comment by wac81** [comment]
thank you again, probably solved most of the problems
