### ISSUE TITLE
The number of input frames?

### ISSUE THREAD

**Issue by Selma-KA** [espnet/espnet#2857]
Hi! 

I'm not sure how many input frames are used for example with VGG. Is the number set as default? If so, what is its value? And how can we reset it? 

Thanks a lot!

**Comment by Fhrozen** [comment]
For training, the input length (number of frames) can vary depending on the data preparation.
For example, you will find the command `remove_longshortdata` in the run of each recipe: https://github.com/espnet/espnet/blob/e9502fc4542b7f4fabfedf60943971d893417874/egs/chime5/asr1/run.sh#L141

For decoding, is almost the same, but there is no limit rather than the memory size (and the processing time) for the input length.
