### ISSUE TITLE
Conformer FastSpeech2 training issue

### ISSUE THREAD

**Issue by joanna-aflr** [espnet/espnet#2891]
Hi, 

I am trying to train a multispeaker GST Conformer FastSpeech2 model from scratch, using [VCTK](https://github.com/espnet/espnet/blob/master/egs2/vctk/tts1/conf/tuning/train_gst_conformer_fastspeech2.yaml) config but with m_ailabs dataset. I successfully trained a Tacotron2 model with the same dataset and I obtained durations from this model for FastSpeech2. I tracked down the issue to [this](https://github.com/espnet/espnet/blob/master/espnet2/tts/fastspeech2.py#L509) line of code. The program throws an error because the dimensions for `hs, e_embs, p_embs` don't match. In my case the program fails when:

p_embs  torch.Size([9, 55, 384])
e_embs  torch.Size([9, 55, 384])
hs  torch.Size([9, 52, 384])

Do you know what could be the reason for this mismatch? I also tried with transformer instead of conformer as the encoder but the issue remains. Thank you!

**Comment by kan-bayashi** [comment]
Maybe you did not use `--use_teacher_forcing` option in decoding of the teacher model.
See https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#fastspeech2-training

**Comment by joanna-aflr** [comment]
Thank you for the reply. I used teacher forcing, the same way as in the example. My commands look like this:

`./tts.sh --nj 48 --stage 7 --stop-stage 7 --cleaner tacotron_de --ngpu $ngpu --fs $fs --n_fft $n_fft --n_shift $n_shift \
  --tts_exp exp/tts_train_raw_char_tacotron_caito_de_en --inference_args "--use_teacher_forcing true" \
  --test_sets "${dset}_eval ${dset}_dev ${dset}_train" --nlsyms_txt "$nlsyms_txt" \
  --feats_type raw --inference_config conf/decode.yaml --train_set ${dset}_train \
  --valid_set ${dset}_dev --token_type char --audio_format wav \
  --inference_model train.loss.best.pth || exit 1;

./tts.sh --nj 48 --stage 5 --ngpu $ngpu --fs $fs --n_fft $n_fft --n_shift $n_shift \
  --feats_type raw --cleaner tacotron_de --inference_config conf/tuning/decode_fastspeech.yaml \
  --train_set ${dset}_train --valid_set ${dset}_dev --test_sets ${dset}_eval --token_type char \
  --audio_format wav --train_config $train_conf --tag $tag --nlsyms_txt "$nlsyms_txt" --srctexts $srctxts \
  --teacher_dumpdir exp/tts_train_raw_char_tacotron_caito_de_en/decode_use_teacher_forcingtrue_train.loss.best --write_collected_feats true`

**Comment by mulgray** [comment]
Hi,

I'm facing a similar problem.
I'm trying to do a fine tuning in FastSpeech2 on JVS with g2p of pyopenjtalk_accent_with_pause.

I first followed [this procedure](https://github.com/espnet/espnet/tree/master/egs2/jvs/tts1) to perform fine tuning from JSUT to JVS, and it worked. I know that both of these configurations are tacotron2 and g2p is pyopenjtalk.

Next, I followed [this procedure](https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/tts1#fastspeech2-training) to train FastSpeech2 on JVS, creating data such as durations by teacher forcing.
```
. /run.sh --stage 7 --tts_exp exp/tts_finetune_jsut_pretrained_tacotron2 --inference_args "--use_teacher_forcing true" --test_sets "jvs010_tr _no_dev jvs010_dev jvs010_eval1"
```
And I can see the training starts successfully with this command.
```
. /run.sh --stage 5 --train_config conf/tuning/train_conformer_fastspeech2.yaml --teacher_dumpdir exp/tts_finetune_jsut_pretrained_ tacotron2/decode_use_teacher_forcingtrue_train.loss.ave --tts_stats_dir exp/tts_finetune_jsut_pretrained_tacotron2/decode_use_ teacher_forcingtrue_train.loss.ave/stats --write_collected_feats true
```
However, in this case g2p is pyopenjtalk, so I added `--g2p pyopenjtalk_accent_with_pause` from stage 5 and restarted it.
```
./run.sh --stage 5 --train_config conf/tuning/train_conformer_fastspeech2.yaml --teacher_dumpdir exp/tts_finetune_jsut_pretrained_tacotron2/decode_use_teacher_forcingtrue_train.loss. ave --tts_stats_dir exp/tts_finetune_jsut_pretrained_tacotron2/decode_use_teacher_forcingtrue_train.loss.ave/stats --write_collected_feats true --g2p pyopenjtalk_accent_with_pause
```
Then stage 5 seems to finish fine, but at stage 6, the dimensions for `hs, e_embs, p_embs` don't match as Joanna mentioned.
```
    hs = hs + e_embs + p_embs
RuntimeError: The size of tensor a (189) must match the size of tensor b (65) at non-singleton dimension 1
```
```
Size([15, 65, 384]) p_embs torch.
Size([15, 65, 384]) e_embs torch.
Size([15, 65, 384]) hs torch.Size([15, 189, 384])
```
Only the second element doesn't match, and I think it's probably token-related, since the second element changes from sample to sample, but I think I've checked that tokens.txt is for pyopenjtalk_accent_with_pause.

If you have any idea what I'm talking about, I would appreciate your advice.

**Comment by kan-bayashi** [comment]
@joanna-aflr Sorry for the late reply.
Hmm. Your command seems valid. Did you change reduction factor?

@mulgray In your case, you need to use the teacher model with `pyopenjtalk_accent_with_pause` since the durations represent that of each token. But the case should raise the error in stage 5. I will check the code.

**Comment by joanna-aflr** [comment]
Thank you for the reply. 

I didn't change the reduction factor. What actually helped was to use a different teacher model to obtain the durations. I am not sure though where was the problem with the approach I posted before. It might have been related to the cleaner function that I modified to include Germanic umlauts in the token list. However, I used the same cleaner for the teacher training as I tried to use for FastSpeech2 training, so I thought it would work. 

Please let me know if you have an idea what might have been wrong. 

Thank you.

**Comment by kan-bayashi** [comment]
> It might have been related to the cleaner function that I modified to include Germanic umlauts in the token list.

Ah ha. Maybe that is the problem.
Did you use the same cleaner in decoding?

**Comment by joanna-aflr** [comment]
Yes, always the same one. But it is likely that it is related to the cleaner because the size of tensor always differed by 1, 2, or 3 and there are 3 additional characters in the German token list. So I'll double check this. 

Thanks for your help!

**Comment by mulgray** [comment]
@kan-bayashi
Thank you for the reply!
As you said, I took a closer look and found that stage 5 also failed.
I downloaded `kan-bayashi/jsut_tacotron2_accent_with_pause` and carefully retried the whole procedure, and it worked fine. Thank you very much.

**Comment by kan-bayashi** [comment]
Maybe this issue is solved. I will close this issue.
