### ISSUE TITLE
Normalization After SpecAug

### ISSUE THREAD

**Issue by sameerkhurana10** [espnet/espnet#2923]
Hi,

I had a question about Espnet2 ASR model. I notice that MVN normalization is applied after SpecAug. See [here](https://github.com/espnet/espnet/blob/master/espnet2/asr/espnet_model.py#L195)

I think this behavior is different from Espnet1. Is that correct?

SpecAug followed by MVN will lead to masked regions to be non-zero, but still constant. Is that okay?

Thanks for the clarification.

**Comment by kamo-naoyuki** [comment]
Oh... thanks. This is a bug.

@sw005320 This bug might change the result.

**Comment by sw005320** [comment]
I see (although I think it would not cause big changes).

**Comment by ronitd** [comment]
Was wondering shouldn't swapping step 2 with step 3 in the espnet_model.py file or alternatively passing the replace_with_zero variable as False while calling the mask_along_axis() function, fix this issue? 
Since SpecAug paper specifically suggests replacing the value with zero since it is the mean value.
