### ISSUE TITLE
Old Docker Version failing recog_wav.sh due to a recent commit to support RNN-T decoding

### ISSUE THREAD

**Issue by siddalmia** [espnet/espnet#2970]
The BeamSearchTransducer function in https://github.com/espnet/espnet/blob/master/espnet/asr/pytorch_backend/asr.py#L38

causes old docker versions to fail which do not have espnet-2 installed. 

@b-flo for the time being would it be okay to move this to - https://github.com/espnet/espnet/blob/master/espnet/asr/pytorch_backend/asr.py#L991

It seems like it's being used only for the RNN-T decoding.

Thanks
Sid

**Comment by b-flo** [comment]
If I understand the issue correctly, it is caused by : [AbsDecoder](https://github.com/espnet/espnet/blob/master/espnet/nets/beam_search_transducer.py#L48) and its import from espnet2 (`from espnet2.asr.decoder.abs_decoder import AbsDecoder`), right?

If so, it should be line should be replaced by `decoder: Union[TransducerDecoderInterface, torch.nn.Module]` and import by `from espnet.nets.transducer_decoder_interface import TransducerDecoderInterface`. 

Sorry, it seems I missed that when I tried to do some unification between espnet1 and 2
