### ISSUE TITLE
Question about transducer nsc beam search

### ISSUE THREAD

**Issue by YoPatapon** [espnet/espnet#3027]
In the implementation of nsc beam search (https://github.com/espnet/espnet/blob/master/espnet/nets/beam_search_transducer.py#L615:L616), it seems like you calculate the blank probability before local pruning which merged line 10 and line 12 of the original algorithm when n_step=1. Why is it equal to the original algorithm? In the original, V should be expanded first and then calculate the blank probability for the complete probabilities.

![image](https://user-images.githubusercontent.com/17683649/109424723-d6211800-7a1f-11eb-8ef7-b19d9afae1bc.png)

**Comment by b-flo** [comment]
Hi,

>  it seems like you calculate the blank probability before local pruning ... 

Blank probabilities for `y'_{i}` hypothesis are computed after local pruning (see L.611-613) when `nstep` > 1. Maybe it's confusing because we don't use `\bar{V}` naming (we reuse `V`) and the same variable name is also used for beam log prob before and after local pruning (l.540 vs L.611).

> Why is it equal to the original algorithm?

I guess you mean "Why is it **not** equal to the original algorithm?" when `nstep` = 1? If so, we added a special case where we allow incomplete hypothesis in `V` (and by extension `B`) to be carried to the next step. Thus, blank probabilities are not computed in that case.
The motivation and explanation will be provided in a future paper but it should be noted that the condition isn't in its complete form here.

Feel free to correct me if I misunderstood your questions!

**Comment by YoPatapon** [comment]
> Blank probabilities for `y'_{i}` hypothesis are computed after local pruning (see L.611-613) when `nstep` > 1. Maybe it's confusing because we don't use `\bar{V}` naming (we reuse `V`) and the same variable name is also used for beam log prob before and after local pruning (l.540 vs L.611).

OK, I see. I noticed another difference. In the original algorithm, before local pruning, complete hypothesis (hyps extended with blank ) are only appended to S and incomplete hypothesis (hyps extended with K tokens) are appended to V. It seems like in your implementation, complete hypothesis are appended to both S and V. Is it also intended?

**Comment by b-flo** [comment]
> It seems like in your implementation, complete hypothesis are appended to both S and V (l.554). Is it also intended?

It's not, it seems to be a mistake introduced in a previous refactor. I only saw it after your initial post, thanks ;)
I'll fix it but note that it won't change anything in terms of performance/speed
