### ISSUE TITLE
OOM Handling during training

### ISSUE THREAD

**Issue by roshansh-cmu** [espnet/espnet#3076]
OOMs can be handled during model training in ESPNet2 by skipping the problematic batch or reducing the batch size dynamically as done in Fairseq here:

https://github.com/pytorch/fairseq/blob/50a671f78d0c8de0392f924180db72ac9b41b801/fairseq/trainer.py#L188

This feature would be useful for ESP2 model training

**Comment by sw005320** [comment]
Year, that sounds very useful option.
One of the most frequent questions is actually about it.
However, this is also useful in general since it lets users know that the data preparation or the batch size is wrong.
But it is still useful to finish it with the correct error message.

**Comment by kamo-naoyuki** [comment]
The implementation is easy. I'll implement it as an option as you request.

I think auto scaling of batch size in lightning is the best way, but this is a little bit hard to implement because we use variable batch size.

https://pytorch-lightning.readthedocs.io/en/latest/advanced/training_tricks.html#auto-scaling-of-batch-size

**Comment by roshansh-cmu** [comment]
The easiest thing might be to just start with skipping the batch, and we can explore changing the batching after I think. Or we can just go through the batch, look for the input with the largest element(s), and run training separately on the remainder and the large elements separately, and make a single model update. Those might be easier than batch scaling
