### ISSUE TITLE
BatchBeamSearchOnlineSim is too slow

### ISSUE THREAD

**Issue by Cescfangs** [espnet/espnet#3100]
`BatchBeamSearchOnlineSim` is about 6 times slower than `BatchBeamSearch` due to repeated labels in hyp, I've recorded search times(method `search()` been called) . For example, to decode hyp "背包客一个比一个年轻":
| 背包客一个比一个年轻     | search times |
| ------------------------ | ------------ |
| BatchBeamSearchOnlineSim | 59           |
| BatchBeamSearch-non-streaming    | 17           |
| BatchBeamSearch-MoChA    | 17           |

**Comment by sw005320** [comment]
Thanks for your report.
Which task are you using?

@eml914, do you know what happened?

**Comment by Cescfangs** [comment]
I am using in-house data for training, the test set is from Aishell-1.
`BatchBeamSearchOnlineSim` assumes repeated labels as a sign to 'waiting' for next chunk and re-search current decoding step using more data, and the repeated labels are pretty common during decoding(`hop_size=10`).

**Comment by eml914** [comment]
Thank you for report.
`BatchBeamSearchOnlineSim` does not decode in streaming way and decoding is not optimized.  So, it is simply for evaluating WER/CERs.
If the repetition occurs frequently, rewrite the following line to `False`
https://github.com/espnet/espnet/blob/ffcf39c27f9aa0cf15c7ae7a06a8a9d35871602e/espnet/nets/batch_beam_search_online_sim.py#L112
This change will ignore the repeated labels.

**Comment by AmirHussein96** [comment]
@eml914  While I was investigating how streaming works I noticed that the encoder encodes the entire speech before it fed to the decoder.  I thought based on the paper (https://arxiv.org/abs/2006.14941) each encoded block is fed to the decoder once they are encoded so that the decoder does not need to wait until the entire segment is encoded. As far as I understand this is not a streaming inference mode, right? If yes, how can I run the model in the streaming inference mode? 

My observation is from the following lines in the `espnet/espnet2/bin/asr_inference.py/` :

# a. To device
batch = to_device(batch, device=self.device)
# b. Forward Encoder
enc, _ = self.asr_model.encode(**batch)
assert len(enc) == 1, len(enc)

# c. Passed the encoder result and the beam search
nbest_hyps = self.beam_search(
    x=enc[0], maxlenratio=self.maxlenratio, minlenratio=self.minlenratio
)
nbest_hyps = nbest_hyps[: self.nbest]
