### ISSUE TITLE
Availability of Voice Conversion recipe in ESPnet2

### ISSUE THREAD

**Issue by Tirthankar-iiitb** [espnet/espnet#3112]
Request update on any planned early release of VC recipe in ESPnet2 for non-parallel corpus.  Have a use case with requirement of many Indian accented English TTS with small train corpus. Planning to use ESPnet2 platform with fine tuning the pre-trained models with non-parallel corpus.

**Comment by sw005320** [comment]
@unilight or @kan-bayashi, can you tell me your opinion about it?
At least, it would be good to have VC with parallel corpora, and I remember that @kan-bayashi once mentioned this possibility.
Also, I think VC with non-parallel corpora in espnet2 would be very valuable, but probably it is not easy to port https://github.com/espnet/espnet/tree/master/egs/vcc20 since the recipe is very complicated.

**Comment by kan-bayashi** [comment]
I made the espnet2-based vc models (taco2, transformer, fastspeech, ...).
https://arxiv.org/abs/2104.06793
But unfortunately this work is supported by the company.
Currently I cannot make the code open-source.
I will discuss with my boss.

**Comment by Tirthankar-iiitb** [comment]
@kan-bayashi: How to use inference on the trained gst_tacotron2 tts/vctk model for style transfer with an unseen reference signal? Thanks for any pointer to this.

**Comment by Tirthankar-iiitb** [comment]
@kan-bayashi: Also, how to specifically choose a few tokens (GST tokens) in the style transfer without using the ref signal using the inference calls in ESPnet Text2Speech? Thanks for your help.
