### ISSUE TITLE
How to map from duration to phoneme location in TTS?

### ISSUE THREAD

**Issue by turian** [espnet/espnet#3132]
I am trying to find where in the final audio, certain phonemes are.

I have already read
https://github.com/espnet/espnet/issues/2839 and am using a transformer.

I am confused tho because durations almost always seems to contain one more entry than the number of phonemes.

Also, there doesn't seem to be a clear mapping between the phonemes and the durations. Sometimes the durations are a few indices off from the phonemes. Also, sometimes the duration is 0? Why?

What is the specific approach to finding the phoneme location in the audio, given the durations?

Or, can I find the specific location of the phoneme in the audio, regardless of durations?

**Comment by kan-bayashi** [comment]
Did you use the output of the duration predictor?

> I am confused tho because durations almost always seems to contain one more entry than the number of phonemes.

That is <eos> symbol.

> Also, there doesn't seem to be a clear mapping between the phonemes and the durations. Sometimes the durations are a few indices off from the phonemes. Also, sometimes the duration is 0? Why?

Since our groundtruth of duration is calculated from the attention weight, i.e., data-driven manner.
Also the durations are predicted in the case of FastSpeech.
Therefore, there is no guarantee of the duration correctness.

> What is the specific approach to finding the phoneme location in the audio, given the durations?

If you want to get precise phoneme alignment, GMM-based force alignment is still the best, I think.

**Comment by turian** [comment]
@kan-bayashi yes, I'm using the durations returned.

Can you recommend a good GMM-based forced alignment implementation for English?

**Comment by kan-bayashi** [comment]
Sorry for the late reply.
https://github.com/pettarin/forced-alignment-tools
This repo helps you.

**Comment by turian** [comment]
Thank you @kan-bayashi
