### ISSUE TITLE
GPU requirement for recipes

### ISSUE THREAD

**Issue by asadolahzade** [espnet/espnet#3139]
Hi,
I'd like to know about the GPU resources (memory, ...) required for running any type of architecture and recipes. Can anyone help me where I can find such information?

Thanks.

**Comment by sw005320** [comment]
I usually use 1080Ti (11GB).
Most of the recipes except for large corpora (e.g., librispeech, gigaspeech, etc.) would work with such a GPU.

**Comment by asadolahzade** [comment]
> I usually use 1080Ti (11GB).
> Most of the recipes except for large corpora (e.g., librispeech, gigaspeech, etc.) would work with such a GPU.

Thank you.
How about LibriSpeech? What resource does it require to train esp. in terms of memory?
Thanks.

**Comment by sw005320** [comment]
I'm using 4 Titan RTX (24GB). Some of the configurations I updated  (e.g., gigaspeech) are based on them.
I used to work with a single 1080Ti (11GB), as well.

Basically, we can make a similar setup across different GPUs by changing the batch size and accum_grad options so that the total batch size (batch size * accum_grad) would be the same.
For example, the current librispeech recipe uses the total batch size = 140,000,000 (140,000,000 * 1).
https://github.com/espnet/espnet/blob/master/egs2/librispeech/asr1/conf/tuning/train_asr_conformer7_n_fft512_hop_length256.yaml#L3-L4
However, if it does not fit your GPU memory (say maximum is 14,000,000), you can increase accum_grad=10.
Then, the total batch size becomes the same (140,000,000 = 14,000,000 * 10), and you can basically reproduce the similar result with your GPU.

**Comment by vrunda-28** [comment]
Hi,
@sw005320 What if I want to use 2 GPU cards instead of 1? For ESPNET2, is this always the case that (batch bins*accum_grad) should be constant **irrespective of the number of GPUs**?

**Comment by sw005320** [comment]
Correct.
So, you can increase them by yourself.

**Comment by Freddy-pp** [comment]
@sw005320, could you please tell, how long and on what system you train Gigaspeech model? Because in conf this info is not provided ("It takes about XX days."). Thanks.

**Comment by sw005320** [comment]
It took 5 days with 4 x NVIDIA TITAN RTX.
