### ISSUE TITLE
Questions about AISHELL-2 recipe

### ISSUE THREAD

**Issue by s920128** [espnet/espnet#3189]
I run the AISHELL-2 recipe from stage 0 to stage 2.
In my train/text the sentence repeat 2 times.
like ` IC0001W0001 厨房用具    IC0001W0001 厨房用具 `
so in data.json of train set, the text and token are repeat 2 times too.
but dev/\*/text or test/\*/text seem to be correct.
I check the stage 0, train/text is correct before run `paste <(cut -f 1 data/${x}/text.org) <(cut -f 2 data/${x}/text.org | tr '[:lower:]' '[:upper:]') > data/${x}/text`
Have you meet the same problem?
I am not sure if it is my environment problem.

By the way, in my train/text the space in two repeat sentence are \t. 
In dev/\*/text and test/\*/text, the format is file_name+\t+text.
but the format in other recipe are use a space  follow the kaldi style.

**Comment by sw005320** [comment]
Thanks for your report.
This would be a bug.

@pengchengguo, could I ask you to check this?

**Comment by pengchengguo** [comment]
Ok, I will check it.

**Comment by pengchengguo** [comment]
Hi @s920128,

Thanks so much for your report. This may due to the format of the transcription file (`AISHELL-2/iOS/data/trans.txt`).

For my Aishell2 data, all files (`trans.txt` and `wav.list`) of all sets (train, dev_ios, dev_mic, etc) are formated as `<uttid>\t<utt>`. And the default delimiter of `cut` command is `\t`. Maybe your `trans.txt` of the training set is like `<uttid> <utt>`. I think you can solve the problem by changing the format of `trans.txt` file.

**Comment by s920128** [comment]
Thanks @pengchengguo !
I re-check my trans.txt.
The format was formated as `<uttid> <utt>` by other people, so result in this problem.
