### ISSUE TITLE
Support for using text directly as input in vcc20 baseline synthesis instead of ASR

### ISSUE THREAD

**Issue by vishal16babu** [espnet/espnet#3206]
I have trained vcc20 baseline for a target speaker. I want to use text to generate voice samples of that target speaker. The baseline for the vcc20 recipe uses ASR on the source speaker speech to get the underlying transcript tokens. 

Is there a way to use text directly to generate the input features for the TTS model? (ASR is very slow and is sometimes inaccurate)

I've tried going through the code and the intermediate results of the ASR stage but couldn't figure out a way to do it. Any help or scripts to generate the ASR stage output directly from text is very much appreciated.

**Comment by unilight** [comment]
> I want to use text to generate voice samples of that target speaker.

So you want to ask how to train a TTS model with your own data, right? There are many TTS recipes, so I suggest you look into them.

**Comment by vishal16babu** [comment]
Hi @unilight ,
I presumed that the vcc20 baseline does just that. I thought it is a TTS speaker adaptation recipe. Am I wrong? I've already trained a bunch of models using the vcc20 baseline so it would help if I can directly use them with modified synthesis stage which uses only text as input.

**Comment by unilight** [comment]
> I presumed that the vcc20 baseline does just that. I thought it is a TTS speaker adaptation recipe. Am I wrong?

I cannot say you are wrong since TTS adaptation is indeed performed as part of the training process, but I would like to emphasize that it is a VC recipe.

> it would help if I can directly use them with modified synthesis stage which uses only text as input.

We currently do not consider officially supporting such a function because it is a VC recipe. However, as I mentioned earlier, there are many TTS recipes available and some of them also perform the adaptation process that you seek for, ex. https://github.com/espnet/espnet/tree/master/egs/arctic/tts1 or https://github.com/espnet/espnet/tree/master/egs/jvs/tts1. I suggest looking into them. Should not be hard for you given that you have already trained a bunch of models.

**Comment by unilight** [comment]
> A hacky way would be to create an eval set with stages 0, 1, 2, 4 and 5. Is there a cleaner way to do it?

To feed the text into the model you certainly need to convert it into `data.json`. You can refer to `utils/synth_wav.sh`, a demo script that takes raw text from the command line. https://github.com/espnet/espnet#tts-demo You can also check the demo notebook. https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb

**Comment by vishal16babu** [comment]
Thanks @unilight , I was able to use the resources and modify the vcc20 recipe to use text as input for inference
