### ISSUE TITLE
Is there any already trained model?

### ISSUE THREAD

**Issue by bluemonk482** [espnet/espnet#322]
Is there any already trained model on conversions in English that I can use off-the-shelf? Thanks.

**Comment by sw005320** [comment]
The most of models I have are based on (old) pytorch 0.3.1. I'm now preparing them with pytorch 0.4.x for Librispeech. @ruizhilijhu, @jnishi, do you have the latest pytorch Librispeech models?

**Comment by ruizhilijhu** [comment]
I don’t have models in librispeech. Most of my experiments are in babel Vietnamese. Harish might have Liberispeech model.@mallidi

**Comment by jnishi** [comment]
@sw005320 I also don't have character model, though I have the subword model with 5000 units.

**Comment by sw005320** [comment]
I just prepared the librispeech model:
- ESPnet version 0.1.5: https://github.com/espnet/espnet/releases/tag/v.0.1.5
- Models: https://github.com/espnet/espnet/releases/download/v.0.1.5/librispeech_asr1.tgz
  - RNNLM: `exp/train_rnnlm_2layer_bs256_unigram2000/rnnlm.model.best`
  - ASR models: `exp/train_960_vggblstm_e4_subsample1_2_2_1_1_unit1024_proj1024_d1_unit1024_location1024_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150_unigram2000/results/{model.acc.best,model.conf}`
- Performance:

|           | WER (%)  |
|-----------|:----:|
| Librispeech dev_clean | 5.0 |
| Librispeech test_clean | 5.0 |

- When we use the above models, please insert the ASR model directory (`expdir`) and RNNLM model directory (`lmexpdir`) in `run.sh` as follows:
```
expdir=exp/train_960_vggblstm_e4_subsample1_2_2_1_1_unit1024_proj1024_d1_unit1024_location1024_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs30_mli800_mlo150_unigram2000
lmexpdir=exp/train_rnnlm_2layer_bs256_unigram2000

        ${decode_cmd} JOB=1:${nj} ${expdir}/${decode_dir}/log/decode.JOB.log \
            asr_recog.py \
            --ngpu ${ngpu} \
            --backend ${backend} \
            --recog-json ${feat_recog_dir}/split${nj}utt/data_${bpemode}${nbpe}.JOB.json \
            --result-label ${expdir}/${decode_dir}/data.JOB.json \
            --model ${expdir}/results/model.${recog_model}  \
            --model-conf ${expdir}/results/model.conf  \
            --beam-size ${beam_size} \
            --penalty ${penalty} \
            --maxlenratio ${maxlenratio} \
            --minlenratio ${minlenratio} \
            --ctc-weight ${ctc_weight} \
            --rnnlm ${lmexpdir}/rnnlm.model.best \
            --lm-weight ${lm_weight} \
```

**Comment by sw005320** [comment]
Yes, as soon as I finished #407, I'll upload the librispeech model.

**Comment by Ruhewang** [comment]
Dear sw005320
Sry for disturbing again, I ran the Stage 0,1,2 & 5 with the trained model above. But in decoding process, it comes error in  decode.1.log:
`# asr_recog.py --ngpu 0 --backend pytorch --recog-json dump/dev_clean/deltafalse/split32utt/data_unigram2000.1.json --result-label exp/train_960_vggblstm_e3_subsample1_2_2_1_1_unit1024_proj1024_d1_unit1024_location1024_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs32_mli800_mlo150_unigram2000/decode_dev_clean_beam32_eacc.best_p0.0_len0.0-0.0_ctcw0.3_rnnlm0.3/data.1.json --model exp/train_960_vggblstm_e3_subsample1_2_2_1_1_unit1024_proj1024_d1_unit1024_location1024_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs32_mli800_mlo150_unigram2000/results/model.acc.best --model-conf exp/train_960_vggblstm_e3_subsample1_2_2_1_1_unit1024_proj1024_d1_unit1024_location1024_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs32_mli800_mlo150_unigram2000/results/model.conf --beam-size 32 --penalty 0.0 --maxlenratio 0.0 --minlenratio 0.0 --ctc-weight 0.3 --rnnlm exp/train_rnnlm_2layer_bs256_unigram2000/rnnlm.model.best --lm-weight 0.3 
# Started at Fri Dec 21 17:55:09 HKT 2018
#
2018-12-21 17:55:09,853 (asr_recog:100) INFO: python path = (None)
2018-12-21 17:55:09,853 (asr_recog:105) INFO: set random seed = 1
2018-12-21 17:55:09,853 (asr_recog:108) INFO: backend = pytorch
2018-12-21 17:55:10,520 (asr_utils:348) INFO: reading a config file from exp/train_960_vggblstm_e3_subsample1_2_2_1_1_unit1024_proj1024_d1_unit1024_location1024_aconvc10_aconvf100_mtlalpha0.5_adadelta_bs32_mli800_mlo150_unigram2000/results/model.conf
Traceback (most recent call last):
  File "/home/user/CARL_remote/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_recog.py", line 120, in <module>
    main()
  File "/home/user/CARL_remote/espnet/egs/librispeech/asr1/../../../espnet/bin/asr_recog.py", line 114, in main
    recog(args)
  File "/home/user/CARL_remote/espnet/espnet/asr/asr_pytorch.py", line 385, in recog
    idim, odim, train_args = get_model_conf(args.model, args.model_conf)
  File "/home/user/CARL_remote/espnet/espnet/asr/asr_utils.py", line 349, in get_model_conf
    return json.load(f, object_hook=AttributeDict)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
# Accounting: time=1 threads=1
# Ended (code 1) at Fri Dec 21 17:55:10 HKT 2018, elapsed time 1 seconds`

1. Can you find any clue from the log above? Is it because I'm using the latest version of Espnet which is different from 0.1.5?
2. Do you have trained English model for version 0.2.0?
Thank you so much and Merry Xmas. XD

Ruhe

**Comment by sw005320** [comment]
> 1. Can you find any clue from the log above? Is it because I'm using the latest version of Espnet which is different from 0.1.5?

Sorry for my late response. I'm not completely sure from the log file, but it should be better to use 0.1.5 consistently. We have changed several data format.

> 2. Do you have trained English model for version 0.2.0?

Now, we're working on version 0.3.0 (#444), and could release the model with that version.
