### ISSUE TITLE
about resume used in chainer

### ISSUE THREAD

**Issue by luweishuang** [espnet/espnet#357]
in src/asr/asr_chainer.py ,I found that resume code as:
    # Resume from a snapshot
    if args.resume:
           chainer.serializers.load_npz(args.resume, trainer)
 and 
       trainer = training.Trainer(updater, (args.epochs, 'epoch'), out=args.outdir) ,
updater is from train_iter and train_iter is training-set related.  Does it means when I don't  change any model network but changing training-set, it will failed to resuming from before snapshot. In fact I have tried this and it does failed. Is there something replaceable solution to do model parameters saving, not dataset involved?

**Comment by sw005320** [comment]
We don't support this function, although several people are working on some adaptation setup where they first read a model and their parameters instead of using a resume function (I believe). You could refer the recognition code, e.g., https://github.com/espnet/espnet/blob/master/src/asr/asr_chainer.py#L490-L502. @creatorscan may know more about this.
