### ISSUE TITLE
Fix accent phrase border in pyopenjtalk_g2p_prosody

### ISSUE THREAD

**Issue by sucveria** [espnet/espnet#3716]
In pyopenjtalk_g2p_prosody of espnet/espnet2/text/phoneme_tokenizer.py, the condition of the accent phrase boundary on the 163st line is
if a3 == 1 and a2_next == 1:
Since there is no distinction between consonants and vowels, the delimiter'#' will be inserted between the consonants and vowels. 
Add the case where the phoneme corresponds to a vowel,  syllabic nasal/N/ and choked sounds/cl/ to the condition,
if a3 == 1 and a2_next == 1 and p3 in "aeiouAEIOUNcl":
Shouldn't it be?
Due to this change, the output example of g2p changes from
e.g. こ、こんにちは -> [^, k, #, o, _, k, o, [, N, n, i, ch, i, w, a, $]
to
e.g. こ、こんにちは -> [^, k, o, _, k, o, [, N, n, i, ch, i, w, a, $]

**Comment by kan-bayashi** [comment]
@r9y9 Could you give your comment?

**Comment by r9y9** [comment]
I am super sorry for being unresponsive. I will look into the issue carefully in a couple of days and keep you updated.

**Comment by r9y9** [comment]
I confirmed that @sucveria's proposed change is right. In my original implementation, the problem only happens if the number of moras is 1 in an accent phrase  (e.g., こ、こんにちは), but it shouldn't do otherwise (e.g., ここ、こんにちは). The problematic cases are rare and I believe it doesn't cause significant impacts for most users. I fixed this in https://github.com/r9y9/ttslearn/pull/29.

**Comment by kan-bayashi** [comment]
Thank you for your confirmation, Ryuichi.
I will follow your modification.
