### ISSUE TITLE
On Real-Time ASR

### ISSUE THREAD

**Issue by dv66** [espnet/espnet#3726]
Hello, 

We are currently using a Bengali ASR model which we trained using espnet's Librispeech recipe [(config).](https://github.com/espnet/espnet/blob/master/egs/librispeech/asr1/conf/tuning/train_pytorch_transformer_lr5.0_ag8.v2.yaml) It works great with very good accuracy levels. On an average we are decoding 10 second long audio clips within 3-4 seconds. We are using cpu-only decoding. 

Now, we are trying to achieve real-time ASR with this setup. We have tried to tweak the decode configs like **beam-size** and others  but we are unable to improve the decoding speed any further. Can you guys help us with your suggestions on this, like how can we perform real-time ASR with espnet, should we go with other recipes or should we make changes to the existing configs. Our goal is to reduce the decoding speed to 1-2 seconds. 

Thank You.

**Comment by sw005320** [comment]
There are several directions (all are in the development stage) 
1. use quantization: this is implemented in epsnet1 but not in espnet2 https://github.com/espnet/espnet/blob/3c30eab699d8c3a0c61331e3cac38050345527de/espnet/bin/asr_recog.py#L282-L289
2. use RNN transducer in espnet1
2. use (block-wise) streaming decoder in espnet2, e.g., https://github.com/espnet/espnet/pull/3614
3. use k2 decoder in espnet 2 https://github.com/espnet/espnet/blob/a0dec2796eac99ca1d5b0c7bfbd35d0c94b996c3/egs2/TEMPLATE/asr1/asr.sh#L100

Again, all items are in the development stage except for RNN transducer, and it would be difficult for you to run them.
Please consider these possibilities and post your progress so that we can help them.

**Comment by BSen007** [comment]
Hi @dv66, I wonder how you calculate RTF for your experiments? Using time command? Thanks

**Comment by sw005320** [comment]
No.
I wanted to mention that RNN-transducer is solid in our implementations.
You could find several examples (e.g., https://github.com/espnet/espnet/tree/master/egs/aishell/asr1/conf/tuning/transducer)

**Comment by mohsen-goodarzi** [comment]
> No. I wanted to mention that RNN-transducer is solid in our implementations. You could find several examples (e.g., https://github.com/espnet/espnet/tree/master/egs/aishell/asr1/conf/tuning/transducer)

Thank you! 👍
