### ISSUE TITLE
Diarization model is NoneType

### ISSUE THREAD

**Issue by JoesSattes** [espnet/espnet#3745]
First of all, I would like to thank you for your contribution to EDA-EEND model. I try to train diarization model without RNN attractor like a SA-EEND by setting None in the attractor configuration based on mini_librispeech/diar1/conf,  NoneType issue is reported. My assumption is this code section that has a return None in attractor_class and then attractor_class try to get value of None.
https://github.com/espnet/espnet/blob/7a1329a6fb713a17f5860ea7aed2315ade8d9860/espnet2/tasks/diar.py#L258-L262

**Comment by sw005320** [comment]
@YushiUeda, could you check this?

**Comment by YushiUeda** [comment]
Thank you for reporting the issue. I will make a PR for fixing this. Sorry for the inconvenience.
FYI, this can be fixed by changing the following 3 parts as follows.

1. https://github.com/espnet/espnet/blob/7a1329a6fb713a17f5860ea7aed2315ade8d9860/espnet2/tasks/diar.py#L84-L91
```
attractor_choices = ClassChoices(
    "attractor",
    classes=dict(
        rnn=RnnAttractor,
    ),
    type_check=AbsAttractor,
    default=None,
    optional=True,
)
```
2. https://github.com/espnet/espnet/blob/7a1329a6fb713a17f5860ea7aed2315ade8d9860/espnet2/tasks/diar.py#L258-L262
```
        if getattr(args, "attractor", None) is not None:
            attractor_class = attractor_choices.get_class(args.attractor)
            attractor = attractor_class(
                encoder_output_size=encoder.output_size(),
                **args.attractor_conf,
            )
        else:
            attractor = None
```
3. https://github.com/espnet/espnet/blob/7a1329a6fb713a17f5860ea7aed2315ade8d9860/espnet2/diar/espnet_model.py#L51
```
        attractor: Optional[AbsAttractor],
```

**Comment by JoesSattes** [comment]
Thank you! It's fixed.
