### ISSUE TITLE
Issue of data preparation in egs/wsj

### ISSUE THREAD

**Issue by Shengqiang-Li** [espnet/espnet#3773]
**Describe the bug**
I have a problem about the  wsj_data_prep.sh in egs/wsj/asr1 of espnet, the information is as follows:

stage 0: Data preparation
Disk id 11_1_1 not found at /home/lsq/espnet/examples/wsj/asr1/local/ndx2flist.pl line 52, <STDIN> line 8.
Warning: expected 7138 lines in train_si84.flist, got 0
Disk id 11_1_1 not found at /home/lsq/espnet/examples/wsj/asr1/local/ndx2flist.pl line 52, <STDIN> line 30295.
Warning: expected 37416 lines in train_si284.flist, got 30278
Disk id 11_14_1 not found at /home/lsq/espnet/examples/wsj/asr1/local/ndx2flist.pl line 52, <STDIN> line 6.

and the code is:

cat links/11-13.1/wsj0/doc/indices/train/tr_s_wv1.ndx | \
 $local/ndx2flist.pl $* | sort | \
 grep -v -i 11-2.1/wsj0/si_tr_s/401 > train_si84.flist

nl=`cat train_si84.flist | wc -l`
[ "$nl" -eq 7138 ] || echo "Warning: expected 7138 lines in train_si84.flist, got $nl"

cat links/13-34.1/wsj1/doc/indices/si_tr_s.ndx \
 links/11-13.1/wsj0/doc/indices/train/tr_s_wv1.ndx | \
 $local/ndx2flist.pl  $* | sort | \
 grep -v -i 11-2.1/wsj0/si_tr_s/401 > train_si284.flist

nl=`cat train_si284.flist | wc -l`
[ "$nl" -eq 37416 ] || echo "Warning: expected 37416 lines in train_si284.flist, got $nl"

cat links/11-13.1/wsj0/doc/indices/test/nvp/si_et_20.ndx | \
  $local/ndx2flist.pl $* |  awk '{printf("%s.wv1\n", $1)}' | \
  sort > test_eval92.flist

cat links/13-34.1/wsj1/doc/indices/h1_p0.ndx | \
  $local/ndx2flist.pl $* | sort > test_dev93.flist

It seems that $local/ndx2flist.pl cannot process the content in wjs0/doc/indices

**Comment by ningbiubiu123** [comment]
Hi, excuse me. Have you solved the WSJ data preparation problem?
I am on the WSJ data preparation, but because forget the data backup and data merged, so don't know the specific data directory, such as the correct file directory is WSJ / 11-13-1 / data, but my file directory is WSJ/wsj0 / data. The WSJ/wsj1 / data, Not knowing the directory structure of the file prevents me from preparing the data. Could you please send me the specific directory structure of WSJ? thank you
