### ISSUE TITLE
The required version for pytorch

### ISSUE THREAD

**Issue by asadolahzade** [espnet/espnet#3842]
Hi there, 
I installed ESPnet2 on my system. My goal task is ASR.  By ```./installers/install_warp-ctc.sh```, I get this:

**Error logs**
```[WARNING] warp-ctc is not prepared for pytorch>=1.7.0 now```

Do I have to install pytorch<1.7.0? 
I ask this because I've noticed that some guys do ASR task while using pytorch>=1.7.0. 

Thanks a lot for any clarification.

**`check_install.py` status **
```
[x] python=3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]

Python modules:
[x] torch=1.10.0+cu113
[x] torch cuda=11.3
[x] torch cudnn=8200
[x] torch nccl
[ ] chainer
[ ] cupy
[x] torchaudio=0.10.0+cu113
[ ] torch_optimizer
[ ] warpctc_pytorch
[ ] warprnnt_pytorch
[ ] chainer_ctc
[ ] pyopenjtalk
[ ] tdmelodic_pyopenjtalk
[ ] kenlm
[ ] mmseg
[x] espnet=0.10.5a1
[ ] fairseq
[ ] phonemizer
[ ] gtn
[ ] s3prl
[x] transformers=4.12.5
[ ] k2

Executables:
[ ] sclite
[ ] sph2pipe
[ ] PESQ
[ ] BeamformIt
```

**Comment by lumaku** [comment]
It depends on how you plan to use espnet.
My setup for ASR is with pytorch 1.10.0 and only the required dependencies for regular espnet 2 ASR.
In most cases, warp-ctc is not needed, as you could use as well either the built-in CTC or other CTC-variants like GTN.
Espnet 2 with the latest pytorch version is already a good setup. 
If I remember correctly, the reasons to use warp-CTC are due to speed and in some use cases, as the Nvidia CTC implementation was limited in label length - but that might not be the case anymore and I'm not aware of any recent benchmarks.

**Comment by asadolahzade** [comment]
> It depends on how you plan to use espnet. My setup for ASR is with pytorch 1.10.0 and only the required dependencies for regular espnet 2 ASR. In most cases, warp-ctc is not needed, as you could use as well either the built-in CTC or other CTC-variants like GTN. Espnet 2 with the latest pytorch version is already a good setup. If I remember correctly, the reasons to use warp-CTC are due to speed and in some use cases, as the Nvidia CTC implementation was limited in label length - but that might not be the case anymore and I'm not aware of any recent benchmarks.

Thank you very much.
