### ISSUE TITLE
use hdf5 at feature dumping and reading

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#412]
@ShigekiKarita and @TsubasaOchiai pointed out the effectiveness of using the hdf5 format. This is one of our old action item, and I want to raise this issue. I found the following source https://github.com/simpdanny/caffe-kaldi/blob/master/kaldi-ark-to-hdf5.py, and it seems that it is very straightforward to call such function in `dump.sh`. Then, in the main ESPnet, we can just read hdf5 files instead of `kaldi_io_py.read_mat`.

**Comment by Fhrozen** [comment]
I did something like that for another code (CHiME3)
I used python to convert the data from the mfcc and store it into h5py.
[mfcc_to_h5.txt](https://github.com/espnet/espnet/files/2380259/mfcc_to_h5.txt)

**Comment by sw005320** [comment]
@ShigekiKarita, do you have comments about it?

**Comment by ShigekiKarita** [comment]
It does not need heavy rewrite in `run.sh` and intermediate files (ark) but `ark,t` should be avoided by [kaldi-io-for-python](https://github.com/vesis84/kaldi-io-for-python) for faster processing.

```
_EXEC_CMMD = '{}/src/featbin/compute-mfcc-feats --config=./conf/mfcc.conf --verbose=2 scp,p:{} ark:- | '
_EXEC_CMMD += '{}/src/featbin/copy-feats ark:- ark,t:{} '
```

**Comment by ShigekiKarita** [comment]
Our preliminary experiment did following steps because hdf5 is little bit complex format to do parallel distributed creation unlike kaldi's scp/ark.
1. create ark files as same as the current recipe in the distributed way
2. convert them into single HDF5 files by `kaldi_io_py.read_scp` and `h5py.create_dataset`
3. replace kaldi_io_py in  `load_inputs_and_targets` with h5py

The problem is, as seen in the first step, there are huge intermediate ark files. I found the [HDF5 file link](http://docs.h5py.org/en/latest/high/group.html#hard-links) like scp is really easy. Maybe the best steps to create HDF5 is as follows
1. create hdf5 files (e.g., data/train/JOB.h5) as same as the current recipe in the distributed way. Here we need to rewrite `kaldi_io_py.write_mat` with `h5py.create_dataset` in compute-fbank-feats.py
2. merge hdf5 files into a single hdf5 file by linking

- src/utils/create-fbank-feats.py modification 
https://github.com/espnet/espnet/blob/afdfa6274a4e5517537358853e4215c8e02cb6db/src/utils/compute-fbank-feats.py#L87-L102
```python
    with h5py.File(args.h5, "w") as f:
        for idx, (utt_id, path) in enumerate(scp, 1):
            ...
            f[utt_id] = lmscp
```

- new script `merge-h5py.py --src train.1.h5 train.2.h5 ... --dst train.h5
```python
import h5py
# argparse options to args ...
dst = h5py.File(dst_path, "w")
for src_path in args.src:
    with h5py.File(src_path, "r") as f:
        for k, v in f:
            dst[k] = v
```

**Comment by kamo-naoyuki** [comment]
@sw005320 
I'm working about #120 now, and as far our DNN-HMM hybrid system, I have already implemented DNN-WPE (based on nara-wpe) + DNN-MVDR (based on Tsubasa Ochiai's code ) joint system with PyTorch. The system seems to work well with Reverb challenge and Chime4 challenge recipes, although the performance is not SOTA.

I'll transport my modules to Espnet and I'm grad if you'll do experiments with them. The beginning of the all,  I'll modify the structure of `data.json` to use `HDF5`, because `kaldi-ark` cannot handle n-dimensional tensor and this is inconvenient to implement multi-channel inputs models.

I talked with @ShigekiKarita about this,  then our proposed structure is:

```json
{
    "utts": {
        "F01_050C0101_PED_REAL": {
            "input": [
                {
                    "path": "asr1/dump/train/feat.h5", 
                    "type": "hdf5",  # I'll support "hdf5", "scp", and "ark" type
                    "key": "F01_050C0101_PED_REAL",  # HDF5 can use any level hierarchy, I think it is better to require "key" attribute, though it may corresponds to the uttid in the many case. 
                    "name": "input1", 
                    "shape": [
                        6,
                        760, 
                        256,
                        2,
                    ],
                   "shape_info": ["channel", "time", "dim", "real_imag"]  # This is meta info to notify its arrangement.
                }
            ], 
```

I think it is better to keep the legacy way to moves things smoothly, so if there are `feat` key as in the past, this format will work in the current way.

```json
{
    "utts": {
        "F01_050C0101_PED_REAL": {
            "input": [
                {
                    "feat": "asr1/dump/train/feat.ark:12345", 
```

**Comment by sw005320** [comment]
@kamo-naoyuki, do you have any update on this direction?

**Comment by kamo-naoyuki** [comment]
@sw005320 No. I don't have much time now. I'm sure to do, please wait 2 weeks at least.

**Comment by sw005320** [comment]
ok.

**Comment by kamo-naoyuki** [comment]
I came back to tackle this. Just a note.

**Comment by sw005320** [comment]
@kamo-naoyuki, OK. Please work on the v.0.3.0 branch.
