### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED while trying multihead attention with Librispeech example

### ISSUE THREAD

**Issue by arkhalid** [espnet/espnet#427]
Hi
I've been trying to run multihead attention for librispeech using docker using 8 GPU with CUDA 9.0 on AWS and received a `CUDNN_STATUS_EXECUTION_FAILED` error after 1500 steps. I appreciate your help and can provide any additional details that are required.

**Comment by Fhrozen** [comment]
Hi there,
It seems an error with the memory. You need to check the length of the utterances and set a maxlen_in, it also may be necessary to reduce the number of files on each batchsize(bs). 
Using location attention, it is possible to train (independent of the number of GPUs) the network with a bs 25, and a maxlen_in of 750. A multihead attention required more memory than the location one, so you need to test bs and maxlen_in parameters in order to avoid this error. You can start with a bs 15 or 10 and check if there is still additional memory you can use.

**Comment by arkhalid** [comment]
Thanks @Fhrozen. I was able to successfully train on a multi-gpu machine running 1080 TI GPUs with nvidia-384 driver. AWS instances have K80 GPU with nvidia-396. It might be difference between  GPUs or Dirver version. I have note been able to isolate that yet. Thanks for your help.
