### ISSUE TITLE
KenLM/ SRILM for decoding

### ISSUE THREAD

**Issue by dneelagiri** [espnet/espnet#429]
Hello,

Is there any plan to support KenLM/SRILM for decoding in ESPnet? CTC supports KenLM when decoding 
https://medium.com/corti-ai/ctc-networks-and-language-models-prefix-beam-search-explained-c11d1ee23306

The training time is much faster than RNNLM

Thanks,
Divya

**Comment by sw005320** [comment]
We'll not support the n-gram LM during beam search to make our beam search algorithm simply in near future. We may support it with n-best rescoring.

**Comment by sw005320** [comment]
Yes, I have to agree that the LM training is slow.
Now, I'm training RNNLM with Librispeech text data (6.6G data without compression) with 5000 subword units, and it would take 3-4 days (see #407, but I internally update several things) when we use batchsize 1024. 
If your data is only 1GB (without compression), it would be less than one day if you use a large batchsize. So, please first test this.

When you use n-gram instead of RNNLM, my suggestion is that you first run the decoding and output nbest (with --nbest option). Then, you rescore the original e2e score with the n-gram for each n-best sequence to get a new result. We don't prepare such functions, and you need to make it by yourself. This rescoring is not a perfect solution, but you can get some reasonable results with minimum efforts.

**Comment by dneelagiri** [comment]
Thank you @sw005320 . I started training using the parameters you used to train Libri data (6.6G). Its interesting that you generated bpe from 960hrs data instead of entire data. Is it because the Network training is with 960 hours and using the bpe units from 6.6G file may impact network training results? If you want I can check generating bpe from 6.6G and training network with it to see, unless you think bpe units should only be generated from audio transcriptions(used for network training)

**Comment by sw005320** [comment]
I actually did not try it, but other people (e.g., @arendu) also suggested to use external text to build bpe. It is great if you try it.

**Comment by dneelagiri** [comment]
I havent seen a considerable improvement by using about 1.5G data apart from Libri data for generating bpe units. There is only about 0.5 reduction in WER on an average.

**Comment by v-yunbin** [comment]
@dneelagiri I have similarity result，rescore has only a little help
