### ISSUE TITLE
Question on RPE for transformer decoder

### ISSUE THREAD

**Issue by helloworld02202** [espnet/espnet#4345]
I can see relative positional encoding (RPE) is used in the encoder side
However, it is not used in the decoder in either self-attention or source-target-attention

Is there any particular reason for this design choice? Will it be supported in espnet in the future?

**Comment by sw005320** [comment]
I don't fully remember the discussion about it.
@pengchengguo, could you answer it for me?

**Comment by pengchengguo** [comment]
Hi @helloworld02202  and @sw005320,

1) Our implementation mainly focuses on the Conformer encoder following the original paper;
2) For the decoder part, it is sometimes hard to use Conformer architecture because its input may be very short (only having one or two characters for a Mandarin sentence), so we keep the Transformer for the decoder;
3) The RPE is proposed in the Transformer-XL and aims to distinguish the same position between different text segments (in Sec 3.3 of Transformer-XL paper). So we didn't include it in the first implementation and I think it may be worth trying. We will conduct some experiments in future work.
