### ISSUE TITLE
Resuming Model from snapshot after increasing the data throwing Error.

### ISSUE THREAD

**Issue by karanMal** [espnet/espnet#475]
**(I am using older version of the Toolkit ).**
I was trying to resume the training from a certain epoch's snapshot but i have to increase the data and then resume training on top of that . When I try this , the following error is being thrown ::

![image](https://user-images.githubusercontent.com/15909866/48967691-7ea6cd00-f00a-11e8-878a-07eca9384034.png)

Any changes did I have to do while resuming ???

**Comment by kan-bayashi** [comment]
This is because current snapshot contains the information about parameters, states of optimizer, and order of iterator.
Therefore, if you change the size of iterator, it causes above errors.
The easiest way is use `torch_load` function instead of `torch_resume`.
In this case, only parameters is loaded. 
(Note that the number of epoch or iteration is initialized.)
