### ISSUE TITLE
CHiME4 Training

### ISSUE THREAD

**Issue by 0x10cx0** [espnet/espnet#527]
Hi there,

I'm new to ASR and trying to use espnet to train models of CHiME4 dataset. I'm confused w/ the training data in the run.sh file. I appreciate it if anyone can help me understand.

My question is that: what are the **tr05_real_noisy**, **tr05_simu_noisy**, **train_si284** data mapping to the chime4 dataset? I can find “dt05_bth, dt05_caf_real, dt05_ped_simu, …” in the isolated folder and other folders, but I don’t know which one is the real_noisy and simu_noisy, train_si284 in your setting? Is it, for example, tr05_real_noisy includes all the tr05_*_real data?

Thanks!

**Comment by sw005320** [comment]
> Is it, for example, tr05_real_noisy includes all the tr05_*_real data?

Yes.

**Comment by 0x10cx0** [comment]
Thanks for the reply. 

I notice in the code that "Additionally use WSJ clean data. Otherwise the encoder decoder is not well trained". Any comments on this? Why do we need the clean data?

**Comment by sw005320** [comment]
This is probably, because, during joint optimization, the attention, and the decoder network training easily gets collapsed by the noises, while the corresponding HMM-based alignment, lexicon, and language model in the hybrid system are separately processed without being affected by noises. Then, we found that mixing clean speech data can well regularize the attention and decoder networks.
