### ISSUE TITLE
Transformer transducer ASR model

### ISSUE THREAD

**Issue by BuaaAlban** [espnet/espnet#5302]
I have searched ibrispeech&aishell in egs/egs2 and I didn't find out any transformer transducer model, is there any pretrained transformer based transducer instead of conformer based transducer in this repo?  
Thanks a lot if anyone knows!

**Comment by b-flo** [comment]
Hi,

> Is there any pretrained transformer based transducer instead of conformer based transducer in this repo?

There is none in ESPnet/ESPnet2 AFAIK. For the encoder, it's usually RNN, Conformer, or Branchformer (and its variants).
If you want to train a Transformer model yourself, you can use the shared version (under `asr`). The standalone version doesn't support Transformer.

**Comment by BuaaAlban** [comment]
Thanks a lot for your relpy, I know the conformer or variants may have better performance, but I wonder why there is no transformer-T even there is lstm-T?
BTW, what do you mean by shared version and standalone version?

**Comment by b-flo** [comment]
> Thanks a lot for your relpy, I know the conformer or variants may have better performance, but I wonder why there is no transformer-T even there is lstm-T

Basically, Transformer was superseded by Conformer/Branchformer in our case. For LSTM, I would say it's mainly due to the research direction we took. It may be useful in some cases such as (extremely) low-footprint ASR but most will prefer to scale/tune down a bigger architecture for their usage/problem (or rely on quantization, smaller datatype, etc).

(Note that what I'm saying is only in regard to the audio encoder. For the Transducer decoder, it's another story)

> BTW, what do you mean by shared version and standalone version?

See [ESPnet2 tutorial](https://github.com/espnet/espnet/blob/master/doc/espnet2_tutorial.md#transducer-asr). Basically, there are two versions of Transducer: one shared with (or built upon) CTC/Attention under `asr` and another one purely aimed at Transducer ASR under `asr_transducer`.
