### ISSUE TITLE
SingingGenerate error TypeError: SVSPreprocessor.__call__() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by peongk** [espnet/espnet#5462]
Hello I am trying to generate samples following the muskits tutorial on SVS but I am getting error above and if i remove parameter "1.0" torch.tensor returns invalid error "Invalid data type str" when trying to tensorify

![Capture](https://github.com/espnet/espnet/assets/90165775/7b9f6717-ff93-4ce8-95aa-64d03f3027e2)

**Comment by ftshijt** [comment]
Hi @peongk , may I ask which tutorial you are following?

**Comment by peongk** [comment]
I am following this demo on muskits' github page https://colab.research.google.com/github/SJTMusicTeam/svs_demo/blob/master/muskit_svs_realtime.ipynb

**Comment by ftshijt** [comment]
Oh I see, as noted in the readme there, the Muskits has been completely merged into ESPnet. During the merging, we did some refactoring over the API which could cause the cross-usage between Muskits and ESPnet.

Therefore, in that case, I would recommend you directly use the ESPnet version instead of following the guidelines from Muskits recpo. For more information of using ESPnet, please refer to doc at https://github.com/espnet/espnet/tree/master/egs2/TEMPLATE/svs1#readme
