### ISSUE TITLE
OWSM training logs

### ISSUE THREAD

**Issue by faroit** [espnet/espnet#5585]
the owsm paper does mention that 

> We will provide reproducible recipes encompassing the entire
pipeline, including data preparation, training, inference, and scoring.
Furthermore, we will release pre-trained models and training logs

is it still planned to release training logs/curves to get some insight on the large runs you guys were doing?

**Comment by sw005320** [comment]
You can find some learning curves etc. in https://huggingface.co/espnet/owsm_v3/tree/main/exp/s2t_train_s2t_transformer_conv2d_size1024_e24_d24_lr2.5e-4_warmup10k_finetune_raw_bpe50000/images

If you need a log, please let us know.
@pyf98, you can provide it.

**Comment by pyf98** [comment]
Hi, I have uploaded the training logs for OWSM_v3. You can find them here:
https://huggingface.co/espnet/owsm_v3/tree/main/exp/s2t_train_s2t_transformer_conv2d_size1024_e24_d24_lr2.5e-4_warmup10k_finetune_raw_bpe50000

There are many log files because we resumed the training many times due to SLURM time constraints and filesystem errors.
