### ISSUE TITLE
text_ctc generation for finetuning OWSM with custom dataset

### ISSUE THREAD

**Issue by Zilai-WANG** [espnet/espnet#5919]
Thank you for providing the tutorial on fine-tuning OWSM with a custom dataset using Espnet-EZ (link: https://espnet.github.io/espnet/notebook/ESPnetEZ/ASR/ASR_finetune_owsm.html). I have a question regarding how to generate the text_ctc for fine-tuning my own dataset. Could you kindly provide any hints or scripts for generating the text_ctc?

**Comment by sw005320** [comment]
Thanks for your feedback.

@Masao-Someki, can you add some descriptions about`text_ctc` (there is no difference in the normal usage, right? (except for the eos symbol for the AED case, but it is handled internally))?
To avoid the confusion, we should even remove the requirement of `text_ctc` and it should be internally hundled.

**Comment by Masao-Someki** [comment]
@Zilai-WANG 
The `text_ctc` is the transcription of the audio. For example, when fine-tuning OWSM for an English-to-German speech translation task, the `text_ctc` is the English transcription, and the `text` is the German translation with special tokens.

Example:
```
text: <eng><st_deu><notimestamps> guten morgen welt
text_ctc: good morning world
```

@sw005320 
> there is no difference in the normal usage, right? (except for the eos symbol for the AED case, but it is handled internally)

Yes, `text_ctc` functions exactly the same as in its standard usage because ESPnetEZ simply takes this data as input and passes it to ESPnet without any modifications. As for the `sos` and `eos` tokens, they are handled internally.

> To avoid the confusion, we should even remove the requirement of text_ctc and it should be internally hundled.

That’s a good idea, and I believe we can handle it internally for ASR tasks. However, for fine-tuning on ST or other tasks, we still need the data from the transcription. How about adding the above description of `text_ctc` in the notebook as a simple workaround? Alternatively, we could consider renaming `text_ctc` to something clearer, like `transcription`.

**Comment by Zilai-WANG** [comment]
thanks so much!
