### ISSUE TITLE
replicating baseline results for WSJ

### ISSUE THREAD

**Issue by shubham-IISc** [espnet/espnet#619]
Hi everyone! I am trying to replicated wsj baseline results with character LM.
Default attention type in the script is "location". But, in RESULTS file, can someone please explain what does the highlighted part mean? Is it multi-head attention with 4 heads?
![image](https://user-images.githubusercontent.com/35381101/53552052-87a2bf80-3b60-11e9-9f21-b1b947287d29.png)

I am achieving WER-9.9 with baseline script rather than 9.3.
Is the multi-head attention being used to achieve 9.3?

**Comment by sw005320** [comment]
I used the location. This degradation might be due to 
1. several internal changes
If you test it with the old version (e.g., https://github.com/espnet/espnet/commit/9b61729d2b2147fc43bc14e4b172d71601aebe94#diff-cd0f4b445a379e6e191f6fcae30782b5), you could reproduce the same result.

2. just due to some randomization. It is very hard to re-produce the same result with this range of the training data.

**Comment by shubham-IISc** [comment]
Thanks @sw005320!! that was helpful!
