### ISSUE TITLE
Is it possible to including kaldi's wfst decoding paradigm to fasten the decoding phrase?

### ISSUE THREAD

**Issue by luckmoon** [espnet/espnet#635]
maybe should tune the wfst because there is no lexicon, context or HMM, but att and ctc.

**Comment by sw005320** [comment]
It is possible, but I'm not sure we can perform some efficient decoding with it. The attention decoder is based on an autoregressive model, which considers whole history in an utterance without the Markov assumption. The beam search with the attention decoder is not input-time-synchronous. We may require a lot of adjustment due to these issues. It is possible to combine it with CTC though.

**Comment by trangtv57** [comment]
hi  @sw005320, 
Can i ask question about what is difference when use WFST combine with CTC and LM decoder beamsearch +CTC (like wav2letter++ using). I get term "context biasing" in [STREAMING END-TO-END SPEECH RECOGNITION FOR MOBILE DEVICES google paper](https://arxiv.org/pdf/1811.06621.pdf) and i want to use it WFST with rnn-transducer but now wfst  with CTC, but i am not sure what is difference or does it can improve result.
thankyou
