### ISSUE TITLE
chainer2pytorch

### ISSUE THREAD

**Issue by sw005320** [espnet/espnet#65]
I'm thinking making a simple converter from chainer-based rnnlm to pytorch, rather than make a pytorch version of a rnnlm training script equivalent to the chainer version. I found https://github.com/vzhong/chainer2pytorch, which seems to be a good example for it. What do you think? @ShigekiKarita, do you have some comments? #53

**Comment by ShigekiKarita** [comment]
It looks nice. I'm also thinking about such a unification. RNNLM is a good start because it is simple indeed.

For long term usage, there can be some hope in ONNX but not matured yet.
+ https://chainer.org/general/2018/01/17/onnx-support-by-chainer.html
+ http://pytorch.org/docs/master/onnx.html

**Comment by ShigekiKarita** [comment]
I mean when chainer supports RNN onnx ops, it is done.  now
+ pytorch is ready (see "The operator set above is sufficient to export the following models:") http://pytorch.org/docs/master/onnx.html#supported-operators
+ chainer is not ready yet https://github.com/chainer/onnx-chainer#connection

**Comment by sw005320** [comment]
@unnonouno do you have comments on a schedule of ONNX RNN support in chainer?

**Comment by mitmul** [comment]
@sw005320 I'm working on ONNX-Chainer, but not yet started making RNN exporting. Because there are several difficulties like how to detect the RNN block from the resulting computational graph generated by Chainer, etc. Could you make an issue in [chainer/onnx-chainer](https://github.com/chainer/onnx-chainer) repository? Let's discuss the design and so on there.

**Comment by sw005320** [comment]
Now we have RNNLM implementation for both chainer and pytorch. We still need such conversions, but close this issue for this particular RNNLM purpose.
