### ISSUE TITLE
Common run.sh and new style egs/asr2

### ISSUE THREAD

**Issue by kamo-naoyuki** [espnet/espnet#820]
In Kaldi/ESPNet style, each `egs` has different `run.sh` even though they are almost all parts are same. 
I think this system is not good for maintenance because all run.sh need to be modified if some new feature are appended. It also makes noises for reviewing when a new recipe is created. cmd.sh, path.sh and conf/slurm.conf etc. are also enough if one exists.

I'm planning that

1. Create it as `asr2` (I won't touch tts because I'm not familiar with it)
1. Kaldi-free (Maybe, just using librosa-FBANK instead of kaldi-FBANK with pitch)#736
1. Use HDF5 insatead of JSON #533
1. New egs structure

(though much not thinking)

```
egs/base (common?template?shared?)
  - asr2/
     | - steps/
          | - data.sh  # Create format data required by ESPNet e.g. data.json
          | - train_lm.sh
          | - train_asr.sh
          | - decode_asr.sh
     | - cmd.sh
     | - path.sh
     | - conf/
          | - queue.conf
egs/wsj
  - asr1/  # Keep as is
  - asr2/
     |- local/
          | - prepare_data.sh  # Create data/
     | - run.sh  #  Invoke train_lm.sh and train_asr.sh, decode_asr.sh
     | - path.sh  # Source ../base/path.sh and set some task depended requirements
     | - cmd.sh -> ../base/run.sh
     | - conf/
          | - queue.conf -> ../base/conf/queue.conf
```

Sometimes, it is necessary to run the only decoding, e.g. for evaluation for speech enhancement, so independent `decode_asr.sh` may be the clear for such people .

**Comment by sw005320** [comment]
Thanks for your great suggestion. 
These are my comments/thoughts:
- I like your idea of working on such a new recipe procedure in `asr2`.
Once we fix it, we can follow the same style for TTS (@kamo-naoyuki and @takenori-y, please watch this issue carefully).
- For `cmd.sh` and `conf/*`, we can put them in the base directory, but I think it's better not to use symlinks because I'm changing them depending on the recipe (e.g., I added more CPU memory requests in `cmd.sh` or `queue.conf` if we use larger data). Do you have any ideas?
- I like the idea of having `data.sh`. It turns out that we don't have so many variations (BPE or not etc.), and we can modularize it.
- I'm a bit hesitating for `train_asr.sh`, `train_lm.sh`, and `decode_asr.sh`. Currently (with your great help), it's just listing the training command with related options and it's quite easy for people to understand what is done by just checking `run.sh`. Separate scripts often lose readabilities. We can find some balance between them.

> Sometimes, it is necessary to run the only decoding, e.g. for evaluation for speech enhancement, so independent decode_asr.sh may be clear for such people.

This is true.
We're now encouraged people to upload the model and this case would be increased. This may be related to @takenori-y's efforts #809.

**Comment by sw005320** [comment]
Another thought.
We can switch from bash to python for the main script, i.e., `run.py` instead of `run.sh`.
Then, we could further modularize the above train, lm train, and decode functions more efficiently.
I'm concerning the compatibility with the main Kaldi bash style, but Kaldi also has such a python main script, and it is possible.

**Comment by kamo-naoyuki** [comment]
> Another thought.
> We can switch from bash to python for the main script, i.e., `run.py` instead of `run.sh`.
> Then, we could further modularize the above train, lm train, and decode functions more efficiently.
> I'm concerning the compatibility with the main Kaldi bash style, but Kaldi also has such a python main script, and it is possible.

I'm against to `run.py`. This is just my experience, but I have many times tackle such challenge in recent years and my conclusion is that shell script way is the best for gluing the training recipe.
Bash has very very restricted functions, so we don't need to use too complex design excessively.

Python can use more flexible design, but it means that it can be more complex. Maybe the kaldi's python script which you means is the nnet3/chain script? But, indeed, it's terrible design. 
There are various level of programmers related to ESPNet,  so  I don't think we can control the balance.

O.K. Basically, I agree your other opinion. I'll tackle to create a PR for discussion based on your comment.

**Comment by sw005320** [comment]
Sounds good.
I also prefer bash gluing and I agree with you but I just raised it because there are always certain amount of requests for making everything with python.

**Comment by ShigekiKarita** [comment]
I agree with @kamo-naoyuki idea. I think async/multi processing in Bash is much easier and readable than one in Python. However, for Jupyter users including me, the handy commands written in Python (data generation, train, decode, scoring) is very welcome.
