### ISSUE TITLE
ErrorCalculator does not work in corpus without <space>

### ISSUE THREAD

**Issue by Pydataman** [espnet/espnet#952]
hello，when I run aishell recipe，error is as follows：

Traceback (most recent call last):
  File "espnet/bin/asr_train.py", line 373, in <module>
    main(sys.argv[1:])
  File "espnet/bin/asr_train.py", line 361, in main
    train(args)
  File "espnet-0.4.0-py3.6.egg/espnet/asr/pytorch_backend/asr.py", line 257, in train
  File "espnet-0.4.0-py3.6.egg/espnet/nets/pytorch_backend/e2e_asr_transformer.py", line 116, in __init__
  File "espnet-0.4.0-py3.6.egg/espnet/nets/e2e_asr_common.py", line 108, in __init__
ValueError: "\<space>\" is not in list

bug?

**Comment by jan-schuchardt** [comment]
Hey, I ran into the same issue with tedlium2. Seems like it is caused by the fact that sentencepiece is now used for token generation.
There no longer is a token "<space>", just normal spaces.
For now, I fixed it by just commenting out 

`self.idx_space = self.char_list.index(self.space)
`
in line 109

and replacing

`if idx != -1 and idx != self.idx_blank and idx != self.idx_space:
`
with

`if idx != -1 and idx != self.idx_blank:
`
in lines 134 and 139. 

Not sure if this is the right approach though, or if something must be changed about the tokenization.

**Comment by kan-bayashi** [comment]
Which version did you use? Could you checkt it via following command?

```bash
cd egs/<some_recipe>/asr1
. ./path.sh
spm_train --version
```

**Comment by kan-bayashi** [comment]
I figured out this issue.
Some corpus does not include the symbol of “<space>”, but `ErrorCalculator` assumes it.
https://github.com/espnet/espnet/blob/9f0729f31bdf4ba6fdc5ca8a48042c9e6f24e00c/espnet/nets/e2e_asr_common.py#L102-L108
@Fhrozen could you fix it?

**Comment by Fhrozen** [comment]
I am checking it now

**Comment by kan-bayashi** [comment]
Fixed in #955
