### ISSUE TITLE
How to assess the result ? 

### ISSUE THREAD

**Issue by robothubtokyo** [espnet/espnet#962]
We trained a language model of English using an4 recipe.
Then we got the tensorboard result, but cannot tell whether it is good or not.
Could you tell me how to assess the result of ESPnet ? 
![result_sample](https://user-images.githubusercontent.com/52391327/61197058-a79cdf00-a70d-11e9-9848-924e26640e1b.png)

Thank you.

**Comment by sw005320** [comment]
Did you train a language model or ASR model? The tensorboard log looks like an ASR model, but you mentioned LM, and I'm confused. To check the result, you should monitor the validation score (validation acc/loss/perplexity) instead of training ones. They have strong correlations to the final applications.

**Comment by robothubtokyo** [comment]
Thank you.
I will check the validation score.
