### ISSUE TITLE
Loss is ok, but grad norm is nan. Do not update model

### ISSUE THREAD

**Issue by Rpersie** [espnet/espnet#964]
Recently, I change some code in the multichannel end-to-end chime4 asr. I estimate the TDOA and improve the beamforming using steer vector. I  check you code and plot the enhanced FFT Spectrogram. I just exit(1) the program after the beamforming. So the figure is just using the initialized parameters and the grad is not updated.The first figure is the espnet results and the second is my improved results. I find my results is better than the espnet. 
The Loss is ok, but it has the warnings in every epoch "grad norm is nan. Do not update model".
Can you give me some advices how to debug it ? Thank you.

![image](https://user-images.githubusercontent.com/12673020/61260340-5b56ab00-a7b0-11e9-8b64-cbf0e40c33e1.png)

**Comment by sw005320** [comment]
Can you check to see the nan issues happening for all iterations or some specific iteration? You could also identify which utterance cases such issues.

**Comment by Rpersie** [comment]
thank you! I have resolved it. Because the eps=1e-15 is too small.

**Comment by ahmedalbahnasawy** [comment]
I'm running RNN-T experiment (phoneme unit)
char_list=['<blank>', '<unk>', '<space>', 'AA', 'AE', 'AH', 'AO', 'AW', 'AX', 'AY', 'B', 'CH', 'D', 'DH', 'EH', 'EL', 'ER', 'EY', 'F', 'G', 'HH', 'IH', 'IY', 'JH', 'K', 'L', 'M', 'N', 'NG', 'OW', 'OY', 'P', 'R', 'S', 'SH', 'T', 'TH', 'UH', 'UW', 'V', 'W', 'Y', 'Z', 'ZH', '<eos>']
I created my own data2json in python to create the train and test json files because espnet deals with char only. 
My conf file is 
[4.layer.blstm.txt](https://github.com/espnet/espnet/files/4432030/4.layer.blstm.txt)

The loss looks fine before epoch 26 but after that i got this warning message then throw KeyError: 'validation/main/loss'
^[[J     total [###########.......................................] 22.46%
this epoch [###############################################...] 95.42%
     40000 iter, 26 epoch / 120 epochs
   0.72085 iters/sec. Estimated time to finish: 2 days, 5:12:31.164863.
^[[4A2020-04-04 15:23:47,966 (e2e_asr_transducer:317) WARNING: loss (=nan) is not correct
2020-04-04 15:23:48,105 (e2e_asr_transducer:317) WARNING: loss (=nan) is not correct
2020-04-04 15:23:48,913 (asr:211) WARNING: grad norm is nan. Do not update model. 
.
.
Exception in main training loop: 'validation/main/loss'

**Comment by b-flo** [comment]
> I created my own data2json in python to create the train and test json files because espnet deals with char only.

You can use phonemes instead of characters, `data2json.sh` has a `--trans_type` option to specify "char" or "phn".

> The loss looks fine before epoch 26 but after that i got this warning message then throw KeyError: 
> ...
 
If validation loss is not correct, an error is thrown. Not sure what was your problem though.

**Comment by ahmedalbahnasawy** [comment]
@b-flo when i make --trans_type=phn all the text replaced to 1. should i convert all the text to phonemes first then run it.  Is my dictionary looks correct ? 
WARNING: loss (=nan) is not correct
WARNING: grad norm is nan. Do not update model.
ERROR : KeyError: 'validation/main/loss'
